### ISSUE TITLE
Add more hooks v3

### ISSUE THREAD

**Issue by Sama34** [mybb/mybb#1151]
Starting from https://github.com/mybb/mybb/issues/882#issuecomment-50003653

**Comment by Destroy666x** [comment]
@Sama34 @mybb/developers What about the duplicate `admin_tools_mailerrors_prune_commit` hook? I'm quite sure it's a bug and should be changed in 1.8.4 - better now than later at least. Otherwise a developer may not notice it and end up with another bug in their plugin. Additionally, I remembered I found another duplicate some time ago - `admin_forum_management_deletemod`:
https://github.com/mybb/mybb/blob/feature/admin/modules/forum/management.php#L437 - deletemod hook for clearing all permissions
https://github.com/mybb/mybb/blob/feature/admin/modules/forum/management.php#L1877 - and deleting a mod

I also remember there were much bigger change for hooks in 1.6.5: http://community.mybb.com/thread-106729.html and some people complained about them. This is nothing compared to that - 2 rarely used hooks will only be affected.

Also, adding hooks to `viewthreadnotes`, `getpmip` and `getip` actions would be nice:
https://github.com/mybb/mybb/blob/feature/moderation.php#L1190
https://github.com/mybb/mybb/blob/feature/moderation.php#L1151
since all the other tools in moderation.php have hooks, no idea why these actions were the only ones omitted.

**Comment by PirataNervo** [comment]
@Destroy666x yeah the one in the maillogs.php should admin_tools_maillogs_prune_commit

**Comment by Sama34** [comment]
I'm kind of surprised about your decision to -_potentially_- break plugins but I agree so I added them to the PR. I also added some I do consider some not mentioned anywhere in this discussion.
