### ISSUE TITLE
Banning list should be descending by default

### ISSUE THREAD

**Issue by mmadhankumar-zz** [mybb/mybb#138]
the banned users list at www.forum.com/modcp.php?action=banning should always be descending by default instead of the current ascending list.

**Comment by clarkolivia321** [comment]
Oh really, you all are right but we have to know that technologies take place for the development of their services giving to the peoples of all over the world, in this way [buy cryptocurrency exchange software](https://cryptoexchangesoftware.net/) because it is the best suggestions for all, as to enhance the social life, they are giving the best, easy and simple ways of services which is essential for Bitcoins software development as well in all over the USA.
