### ISSUE TITLE
openssl_random_pseudo_bytes slow on Windows

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1815]
It may even exceed the execution time: http://community.mybb.com/thread-165567-post-1137862.html#pid1137862 so not sure if we should use it as the first choice on Windows (probably we should just siwtch the order of conditionals).

**Comment by euantorano** [comment]
Seems to be an issue with OpenSSL, not PHP specifically. Apparently, there's not much difference in terms of security in `mcrypt_create_iv` and `openssl_random_pseudo_bytes`. Might be better to use the `mcrypt` option as the preference...

**Comment by Stefan-ST** [comment]
@euantorano Just preferring mcyrpt will cause the same issue in case mcrypt in not available. Either we have to remove it or keep it and say it's a host specific issue.

Since similar code is used by other projects ([Drupal](https://github.com/drupal/drupal/blob/84092f3d051c7d8904a63d38c81eb5f671b6e71b/includes/bootstrap.inc#L1998), [Dropbox-SDK](https://github.com/dropbox/dropbox-sdk-php/blob/728ba7ddc212657eb5fdc5c3b23f067740c95aee/lib/Dropbox/Security.php#L52)) while other don't use it on windows at all ([Typo3](https://github.com/TYPO3/TYPO3.CMS/blob/095955bea743c46ad6d6208f40e9bcdd91608915/typo3/sysext/core/Classes/Utility/GeneralUtility.php#L1154)).

**Comment by euantorano** [comment]
Good point Stefan. Not sure what the best approach is. Obviously we can't have it timing out. Maybe just have a check for Windows and skip calling the OpenSSL function if true?

**Comment by Destroy666x** [comment]
We already have a check for Windows: https://github.com/mybb/mybb/blob/feature/inc/functions.php#L7550 But skipping it seems to be the most reasonable solution, yes.

**Comment by Destroy666x** [comment]
There are also 2 other Windows-compatible generation methods mentioned here: http://stackoverflow.com/questions/8553644/accessing-cryptgenrandom-from-php but they don't really seem reliable either.

**Comment by Destroy666x** [comment]
This was corrected (the order at least) and I don't think that more can be done, so closing.
