### ISSUE TITLE
Userhandler still doesn't delete some stuff

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1820]
Removal of the following content is missing after merging https://github.com/mybb/mybb/pull/1819:
- [x] attachments - records in `attachments` table and files
- [x] pollvotes
- [x] announcements
- [ ] ~~PMs~~ Moved to #1112
- [x] referrals (`referrer` column)

**Comment by Sama34** [comment]
>attachments - records in  attachments  table and files
 pollvotes
 announcements

Should be removed only if we are deleting posts/threads.

> PMs

This was already correct in the core:
`$db->delete_query('privatemessages', "uid IN({$this->delete_uids})");`

With your updated code you are now deleting content in another user's account, which shouldn't be.

**Comment by Destroy666x** [comment]
> This was already correct in the core

No, it isn't. As @Stefan-T said, they should be deleted by Purge Spammer (and on similar occassions), you don't want to leave spam PMs sent out to members..

**Comment by Sama34** [comment]
So you (the admin) designated what is considered spam for my (the not spammer user) inbox? Right then.

**Comment by JN-Jones** [comment]
If I (as admin) use the purge spammer tool on that user - yes.

**Comment by Destroy666x** [comment]
If you're using Purge Spammer on a user then you're considering that his content was inappriopriate for the forum and it's better to get rid of it completely. PMs can be abused as easily by bots as threads/posts. As admin I wouldn't want to have to use phpMyAdmin to remove them when there is a tool that's supposed to clear everything.

**Comment by Sama34** [comment]
> If I (as admin) use the purge spammer tool on that user - yes.

The data-handler methods used to delete user's content are not explicitly and only used for the PS feature.

This also demonstrates, IMO, why there were select boxes in the former implementation of the feature that were later removed because, well, sending an _user_ to the _spam database_ always mean to delete all of its content blindly, apparently.

#1112

> As an admin I wouldn't want to have to use phpMyAdmin to make them disappear when there is a tool that's supposed to clear everything.

I (as an admin) would never bother to affect my users' personal data such as their PMs assuming I know what is spam and what is not. IIRC there is a report, search, and delete feature, they can report a spammer and then search for all PMs from that user and delete them all personally and accordingly.

**Comment by Destroy666x** [comment]
> The data-handler methods used to delete user's content are not explicitly and only used for the PS feature.

That doesn't mean we can't add another function that would be called only here: https://github.com/mybb/mybb/blob/feature/moderation.php#L2787 and in the `else`.

> This also demonstrates, IMO, why there were select boxes in the former implementation of the feature that were later removed because, well, sending an user to the spam database always mean to delete all of its content blindly, apparently.

Well, they were removed because most of us thought they're not useful for anything, iIrc.

> IIRC there is a report, search, and delete feature, they can report a spammer and then search for all PMs from that user and delete them all personally and accordingly.

You forget that not all people who use forums are keen on computers that much to be able to detect a spammer on the first sight. Another example - what if a human spammer sent a convincing mass PM with a link to a virus? I think many users would just blindly open the link instead of manually deleting the PMs. Again, one click to get rid of them would be helpful here.

**Comment by Sama34** [comment]
THat is assuming, again, the feature tool and code methods are solely used to affect _spammers_.

**Comment by JN-Jones** [comment]
Why do we even need to discuss this? We have the delete_user method as main method to delete the user and it's data (like profile fields etc) and the delete_content which deletes **all** data/content associated with that account (like posts etc). When I decide to delete a user **and** his data the PMs send by him should be deleted too (eg when using the purge spammer feature). However when I only want to delete the user **and not** his content the PMs should be kept.

**Comment by JN-Jones** [comment]
As I can't edit my previous post from my phone: delete_content is actually the wrong function, meant delete_posts here. Which should probably be renamed as it already deletes reports too.

**Comment by Sama34** [comment]
> When I decide to delete a user and his data the PMs send by him should be deleted too

When I delete my e-mail account do you expect all e-mails sent to you from my account to just disappear? I wouldn't if it was your account the one being deleted I would want every single message you sent to me to stay where I keep them.

**Comment by Destroy666x** [comment]
Deleting your own account ≠ deleting someone's account. The first is unreliable and impossible in the MyBB core, the second is done by admins (who are in charge of their forum) and if they feel that an user should completely disappear from their board, then every trace should be removed, not only 95.6%. And if admins use Purge Spammer for "banning" regular users or anything else that's unintended and may result in losing valuable PMs - well, they can do more stupid things than that if they really want to...

Also, the old Goodbye Spammer plugin had sent PM deletion option too and I never heard anyone complaining about that: https://github.com/MattRogowski/Goodbye-Spammer/blob/master/files/inc/plugins/goodbyespammer.php#L306 but we forgot to implement it to the userhandler when the plugin was included.

**Comment by Sama34** [comment]
> Deleting your own account ≠ deleting someone's account.

Focus on the deletion of content, not the difference of actions.

I'm not against deleting PMs of the user being marked as spammer, but the deletion of PMs sent by them being deleted is what concerns me.

> if they feel

They don't have a choice, after all you (dev/us) are deciding how it should be. You are deciding than an user being deleted in X board should remove (possible legitimate) PMs in others users imbox without an option to negate that.

It is like deleting an user thread with all post within in ignoring the useness of replies, but well that is already implemented since the beginning so there is not much to discuss (ideally you should have the option to convert the subsequent post into the thread first post and update it propertly as some people have already suggested before).

> and I never heard anyone complaining about that

Never anyone complained about the current core not deleting PMs sent by spammers in other's imbox yet someone (you) suggested and decided to apply the change without considering discussion on less than 24 hours.

I'm here to discuss the change on that line, because I'm against it.

Then again, probably I'm the only here interested on discussing changes so whatever. It seems to be 2 (~3) / 1 so unless someone jumps in you win go ahead if you want.

**Comment by JN-Jones** [comment]
Deleting your own account isn't our responsibility as it's not possible. Also that would fall under "delete user without content"...

**Comment by Sama34** [comment]
This should be done. Most content doesn't require removing but updating the UID suffices.

**Comment by Destroy666x** [comment]
If `$prunecontent` is set to 0 then yes, but your PR doesn't do anything when it's 1. It should remove attachments/votes/announcements + possibly PMs if there are more people that don't disagree, which is the main point here.

**Comment by Sama34** [comment]
> your PR doesn't do anything when it's 1

The moderation class handles that.

> possibly PMs

Should only be deleted if the user is an spammer so I moved it to a more proper issue.

**Comment by Destroy666x** [comment]
> The moderation class handles that.

Where? I guess you mean `delete_thread()`, but the deleted user can vote in polls outside of own threads (which won't be deleted by userhandler). And announcements aren't touched by that function at all.

Attachments on the other hand can probably be skipped, since only orphaned ones may be left in db/filesystem and the ACP functionality takes care of that.

**Comment by Sama34** [comment]
If I recall correctly this was ready to merge (after testing). Please bug me if I missed something.

**Comment by Destroy666x** [comment]
https://github.com/mybb/mybb/pull/1919/files#diff-d7a79d2018f59155db42272766f2f79bR1473
Doesn't `fromid` equal to `0` mean it's sent by MyBB Engine? Deleted users have already been covered more or less correctly by MyBB: https://github.com/mybb/mybb/blob/feature/private.php#L1081-1089

**Comment by Sama34** [comment]
> posts are deleted by `delete_thread()`

Threads started by the user, not all threads. The report delete query part is redundant yes.

I have opened the proper issues for your suggestions.
