### ISSUE TITLE
Add file name and file size to image attachment tooltips

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#1877]
As the title says.

**Comment by Sama34** [comment]
#1867

**Comment by Destroy666x** [comment]
Don't know why keep assigning me to issues I didn't fix though: http://community.mybb.com/thread-153813.html

> The developer fixing an issue should be assigned to that issue The SQA member testing the fix should be assigned to the Pull Requests.

**Comment by Sama34** [comment]
Because the issue lacks an assigned person? And you are responsible for the issue because, well, you created it, accepted the PR and merged the PR, and closed the issue?

I mean, you handled the issue almost totally by your self (_team members_). I consider you responsible for this so I assigned you to it, but if you don't want your name to appear in a field that is up to you.

**Comment by Destroy666x** [comment]
Read again (?) what I quoted above...

Issues (so this) should be assigned to the "developer fixing an issue" - so a person who opens a PR for it.
Pull Requests (so the code I merged) are assigned to the person who merges them - and I already assigned myself.

That's how our guidelines always worked and that's all.
