### ISSUE TITLE
Soft Delete option in custom mod tools doesn't work 

### ISSUE THREAD

**Issue by PaulBender** [mybb/mybb#1882]
The Soft Delete option in custom mod tools doesn't work when you run that tool. Affects both Thread and Post tools.

**Comment by Cu8eR** [comment]
@PaulBender - soft delete issue is still not fixed - I disabled it in my board but I can still see soft delete thread/post and perform this action. I cannot find last issue here (on mobile)

**Comment by Stefan-ST** [comment]
@Cu8eR There is no option to disable soft delete globally.

**Comment by Cu8eR** [comment]
I know, so it would be nice to have this setting.

**Comment by Destroy666x** [comment]
I see no reason for a setting that fully enables/disables soft deletion. Other moderation tools don't have such options either.

The only thing I'd add is a setting for default behaviour of the Delete button in posts (when both hard and soft deletion are available for a mod/admin) because there were some questions about it:
http://community.mybb.com/thread-167454.html
http://community.mybb.com/thread-167243.html
Should be easy enough.

Anyways, this isn't a good place to discuss it, feel free to suggest it on forum.
