### ISSUE TITLE
all logins A valid method was not supplied to the data handler.

### ISSUE THREAD

**Issue by Ap0x** [mybb/mybb#1887]
i today 1.6 to 1.8.3 upgrade then i see this errors from login forums.

A valid method was not supplied to the data handler.

how to fix this bug ?

**Comment by Nik101010** [comment]
First of all - please read the contribution guidelines (https://github.com/mybb/mybb/blob/feature/CONTRIBUTING.md) - new issues should be reported on the community forums...

The login works fine, otherwise there would have been more reports. So it seems this is an issue limited to your board. Please use the upgrade support forum (http://community.mybb.com/forum-182.html) instead of opening bug reports here on GitHub.
