### ISSUE TITLE
Referrals Are Lost on Account Merge

### ISSUE THREAD

**Issue by PaulBender** [mybb/mybb#2020]
As the title says.

If account A has 6 referrals and is merged into account B with only 1 referral then it will still only say they have 1 referral.

It should carry over IMHO, same with reputation actually.

Original thread: [Referrals Are Lost on Account Merge](http://community.mybb.com/thread-167259.html)

**Comment by Destroy666x** [comment]
Note there are also 3 bugs mentioned in this post: http://community.mybb.com/thread-167259-post-1141300.html#pid1141300
- [ ] only added reputation is checked for duplicates, received should be also verified: https://github.com/mybb/mybb/blob/feature/admin/modules/user/users.php#L1964
- [ ] but added reputation isn't even checked properly - it relies on neighbouring UIDs, but the query doesn't sort results by UID
- [ ] this check is wrong: https://github.com/mybb/mybb/blob/feature/admin/modules/user/users.php#L1974 and removes the current valid reputation if the last reputation was invalid (why?)

**Comment by JordanMussi** [comment]
This should be reopened as it hasn't been fixed properly.

In #3405 the `referrer` field is updated in the same way as `referrals`. `referrer` holds the uid of the referring user and `referrals` holds the count of users referred.

https://github.com/mybb/mybb/blob/be77219bc70d7a9df2c7c7375d69c682c4aad139/admin/modules/user/users.php#L1979-L1981

Users who were referred by the source user are left hanging and not recorded as referred by the destination user.

If the source or destination user referred the other then the referrals will be incorrect after the merge as well.
If the destination user was referred by the source user then it should be updated to be referred by the user that referred the source user.
If the destination user wasn't referred it should be changed to the user that referred the source user (as long as it was not the destination user).

I'm sending a PR to correct this 😃

Unfortunately there isn't a way to recover referrers of users previously merged in this incorrect way except for using the admin log which may not be a complete record. Is it worth attempting to restore some of the lost information using the admin log in the upgrade script?

**Comment by yuliu** [comment]
> This should be reopened as it hasn't been fixed properly.
> 
> In #3405 the `referrer` field is updated in the same way as `referrals`. `referrer` holds the uid of the referring user and `referrals` holds the count of users referred.
> 
> https://github.com/mybb/mybb/blob/be77219bc70d7a9df2c7c7375d69c682c4aad139/admin/modules/user/users.php#L1979-L1981
> 
> Users who were referred by the source user are left hanging and not recorded as referred by the destination user.

Good catch! I suggest creating a new issue to address the problems.

> I'm sending a PR to correct this 😃

And thanks for that!

> Unfortunately there isn't a way to recover referrers of users previously merged in this incorrect way except for using the admin log which may not be a complete record. Is it worth attempting to restore some of the lost information using the admin log in the upgrade script?

I don't think we should do this. Three reasons:
- We don't need to. (_What kind of reason it is.._)
- Admin logs may not be complete, meaning that we maybe can't find each an every record for fixing historical mistakes since it can be purged (automatically by default).
- The design of the upgrade script doesn't prevent itself from being executed multiple times natively, unless we compare `version` and `version_history` in table `datacache`. (Maybe related to https://github.com/mybb/mybb/issues/2116#issuecomment-636465455 ?)

Let's get this discussion in your new issue, please.

**Comment by JordanMussi** [comment]
New issue at #4036

I do think an effort should be made to correct any problems from previous merges. Of course in some cases the logs will have been trimmed so not every merge can have the information recovered. It doesn't matter if the upgrade script is run several times as the loose data would have been fixed.

What we can't recover is the original referrer of x or y since the two uids were added together. So it would possibly be best to set to 0.

What I am imagining is for admin log entries where user x was merged into user y:
- users referred by x will still have `referrer` set to x so can be changed to y
- recount y's referrals by counting number of users with `referrer` as y
- possibly set y's referrer to 0 as it would have been set wrong

After this process running a second time:
- no users will have `referrer` set to x
- recount will not make a difference
- y's referrer will already be 0
