### ISSUE TITLE
Mssing using_remote_avatar language string.

### ISSUE THREAD

**Issue by JN-Jones** [mybb/mybb#2077]
Apparently the 'using_remote_avatar' message string is missing in the code. Used in usercp.php

Original thread: [Mssing using_remote_avatar language string.](http://community.mybb.com/thread-168364.html)

**Comment by Naththo** [comment]
Thinking of what to add for this.

I thought about `You are currently using an image from a remote site. If you choose to use another one, the remote URL will be removed.`

**Comment by Destroy666x** [comment]
That or something similar, yes. I'd say:
`You are currently using an image from a remote site. If you choose to use another one, your old URL will be overwritten.`

**Comment by Destroy666x** [comment]
I'd also change the other `already_uploaded_avatar` error because it's incomplete. It says `You are currently using an uploaded avatar. If you upload another one, your old one will be deleted.` but if you enter a remote URL, the old avatar will still get removed (you don't need to upload an avatar).
