### ISSUE TITLE
Sending message to myself with BCC will cause an error

### ISSUE THREAD

**Issue by JN-Jones** [mybb/mybb#2093]
I (Jones) send a message to myself with another user as BCC. When I'm using the Quick Reply (not sure whether the full reply has the same error) to answer (still logged in as Jones) it will cause an error: "[...] Invalid recipients: &lt;!-- start: private_read_bcc --&gt; &lt;br /&gt;BCC: &lt;a href=". Likely a variable is used twice.

Original thread: [Sending message to myself with BCC will cause an error](http://community.mybb.com/thread-159036.html)

**Comment by JN-Jones** [comment]
Note that I've also mentioned another cause there.

**Comment by Naththo** [comment]
It seems that the issue is `$bcc` is made up of links from build_profile_link() [L1121](https://github.com/mybb/mybb/blob/feature/private.php#L1121) so it gets escaped. I'm not sure what the best way to go about this is. I thought about adding `$bcc_form_val` and then just adding the username to it and changing [this](https://github.com/mybb/mybb/blob/feature/install/resources/mybb_theme.xml#L10110) line to `$bcc_form_val`. 

Or we could change $bcc_recipients to an associative array.

Not sure the best way to go for this.

**Comment by Destroy666x** [comment]
@Naththo, you're correct about the cause (the whole template HTML is used: https://github.com/mybb/mybb/blob/feature/private.php#L1134) and adding a variable to store clean usernames is a reasonable solution.
