### ISSUE TITLE
Unable To Perform a Database Backup

### ISSUE THREAD

**Issue by JN-Jones** [mybb/mybb#2125]
ACP -&gt; Tools &amp; Maintenance -&gt; Database Backups -&gt; Select All -&gt; Perform Backup.

The download will begin, the archive file downloaded will be damaged.
However, changing the Save Method to Backup Directory will solve the issue.
Other noticeable thing is, the archive downloaded will be much larger than the one saved to the Backup Directory.
Downloading from Backup Directory to the computer has no issues.

Original thread: [Unable To Perform a Database Backup](http://community.mybb.com/thread-162947.html)

**Comment by JN-Jones** [comment]
Note: only the archived file is corrupted and only if you download it directly.

**Comment by frostschutz** [comment]
It's larger because `gzencode()` compresses every string individually on its own (and `clear_overflow()` is called for every little string), whereas `gzwrite()` is a proper stream that takes previous strings into account. So twenty gzwrite() calls may cause 1 byte output (if it's 'aaaaaa') but twenty gzencode() calls will cause 20 byte output.

Not sure why it would be corrupt but as always with PHP processing if some other plugin or file causes unexpected output, it may corrupt the download.

**Comment by JN-Jones** [comment]
I've only checked it with a fresh installation and WinRAR said that the file is corrupted. Haven't checked the cause but there's clearly something wrong.

**Comment by frostschutz** [comment]
If you upload a corrupted file I'll have a look

**Comment by frostschutz** [comment]
unless the issue is simply this:

<pre>
echo gzdecode(gzencode('a').gzencode('b'));
a
</pre>

real gzip is fine with that, though:
<pre>
php > file_put_contents("something.gz", gzencode('a').gzencode('b'));
shell $ gunzip < something.gz 
ab
</pre>

Technically, concatenating gzip is allowed. In practice not every software may like it though.

**Comment by Devilshakerz** [comment]
The compressed data would have to go through the filesystem to prevent hitting the memory limit, which would take care of the broken archives problem and would decrease the file size, but it couldn't be instantly streamed anymore (the plain `.sql` mode wouldn't be affected).

**Comment by Shade-** [comment]
I wonder why this hasn't been patched already. I'd say it's critical priority; ran into a database failure playing around with my board, but I dumped the database using the built in tool before doing so. Long story short, I've lost everything and could not restore the backup due to the file being corrupted.

**Comment by ezeql** [comment]
@Shade- 

I hit the same problem but i'm not able to fix it by removing the characters.

I'm getting: gzip: stdin: invalid compressed data--crc error

any hints? Thanks!

**Comment by frostschutz** [comment]
@Shade what kind of plain text was it and where did it come from? sounds more like you have some php file misbehaving. (like the utf-8 byte order mark issue people get when editing files with MS notepad). Unwanted output is a common issue with PHP. The fault is with broken PHP files, not MyBB itself...

@ezeql `hexdump -C -n 16 thefile.gz`? should start with 1f 8b whatnot ... 

```
$ echo Hello World | gzip | hexdump -C -n 16
00000000  1f 8b 08 00 b2 5b 23 58  00 03 f3 48 cd c9 c9 57  |.....[#X...H...W|
00000010  08 cf 2f ca 49 e1 02 00  e3 e5 95 b0 0c 00 00 00  |../.I...........|
00000020

```

**Comment by ezeql** [comment]
`➜  mybb hexdump -C -n 16 backup_3a3139f390aH6bFP3ZSUyXaY4Bt0ovmE68UWtjk7wpp5JMmv8Thr5LPLtX3Uf6gp\ \(copy\).sql.gz
00000000  1f 8b 08 00 00 00 00 00  00 03 f3 f4 0b 76 0a 51  |.............v.Q|
00000010`

**Comment by ezeql** [comment]
more info:

text contents at the beginning of the file:

`-- MyBB Database Backup
-- Generated: 08th November 2016 at 02:06
-- -------------------------------------

CREATE TABLE `mybb_adminlog` (
  `uid` int(10) unsigned NOT NULL DEFAULT '0',
  `ipaddress` varbinary(16) NOT NULL DEFAULT '',
  `dateline` int(10) unsigned NOT NULL DEFAULT '0',
  `module` varchar(50) NOT NULL DEFAULT '',
  `action` varchar(50) NOT NULL DEFAULT '',
  `data` text NOT NULL,
  KEY `module` (`module`,`action`),
  KEY `uid` (`uid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;`

**Comment by Shade-** [comment]
@frostschutz Same text @ezeql wrote.

**Comment by ezeql** [comment]
@Shade-  I'm confused. Were you able to recover the backup ?

**Comment by Shade-** [comment]
I was. Just delete that part from the backup and decompress using The Unarchiver (using Mac). gunzip did not work even after the removal much to my surprise.

**Comment by Stefan-ST** [comment]
@Shade- Does gunzip work with backups created after applying the fix?

**Comment by Shade-** [comment]
Confirmed to work on 1.8.8.

**Comment by ezeql** [comment]
@Stefan-ST  seems to work on an almost clean installation.

**Comment by ezeql** [comment]
@Shade- Tested using  your suggested app and it didn't work :(

**Comment by Shade-** [comment]
If you want, you can send me a temp link to download the backup and I will try to recover it for you.

**Comment by ezeql** [comment]
@Shade-  much appreaciated. I sent you a pm at the forum.

**Comment by frostschutz** [comment]
For the case where it starts with plaintext and then turns into gzip stream later on, some manual recovery steps using Linux / binwalk / dd / gunzip: http://unix.stackexchange.com/a/282374/30851

**Comment by ezeql** [comment]
I was able to recover my data after @frostschutz  suggestions.

Thank You !!!!
