### ISSUE TITLE
Report notifications ignore moderator groups

### ISSUE THREAD

**Issue by Stefan-ST** [mybb/mybb#2370]
This query in inc/functions_modcp.php just checks for users moderating the forum but not for groups:
```php
	if(!empty($forum['parentlist']))
	{
		$query = $db->query("
			SELECT DISTINCT u.username, u.email, u.receivepms, u.uid
			FROM ".TABLE_PREFIX."moderators m
			LEFT JOIN ".TABLE_PREFIX."users u ON (u.uid=m.id)
			WHERE m.fid IN (".$forum['parentlist'].") AND m.isgroup = '0'
		");

		$nummods = $db->num_rows($query);
	}
```
There is no code for isgroup=1.

**Comment by Destroy666x** [comment]
The fix is quite simple, but I'm also wondering what's the purpose of running the other query only when the previous one has no results: https://github.com/mybb/mybb/blob/feature/inc/functions_modcp.php#L161
So admins/super mods get notifications when:
- it's a profile/reputation report
- there's no moderator for the forumlist
But they don't get anything if there is at least one moderator. Why? Is it intentional (doesn't make any sense to me)?

**Comment by Stefan-ST** [comment]
I think it is intentional but it doesn't make much sense to me either.

**Comment by Destroy666x** [comment]
I've already corrected it since I don't think there's any explantation for it being intentional
