### ISSUE TITLE
Ability to disallow remote avatars

### ISSUE THREAD

**Issue by Devilshakerz** [mybb/mybb#2413]
It should be possible to disable adding remote avatars in User CP (there also could be an option to let MyBB download and store them locally).

http://community.mybb.com/thread-171303-post-1160778.html

**Comment by kawaii** [comment]
+1 for this. A lot of forums have problems with their backend systems address space being leaked and attacked directly, negating the use of reverse proxies etc.

**Comment by euantorano** [comment]
Unfortunately this won't fully fix that. Any emails sent from your board will still include your IP address unless you use a service that strips the originating servers details from all sent email headers. 

It will help, but this won't be a silver bullet to fix all.

**Comment by JoshHarmon** [comment]
How do we want to handle remote avatars currently set for users? Blank the database field and let the default avatar be displayed?

**Comment by kawaii** [comment]
@JoshHarmon I would leave them as they are but give the admin an option to truncate that column or blank it as you said.

**Comment by Devilshakerz** [comment]
It could also show the default avatar instead and a warning in the User CP until they upload one or remove it.

**Comment by Sama34** [comment]
We could add a simple tool that removes all remote avatars yes, it could be useful even if administrators don't disable them altogether.

**Comment by Cu8eR** [comment]
I think this is one of the most useful features for MyBB - it could enhance the security

**Comment by JN-Jones** [comment]
@euantorano Another avatar related issue you're assigned to :P

**Comment by euantorano** [comment]
Yep, I'll look into it this week :)

**Comment by XIII-13** [comment]
+1 for this. I think it would be very useful and a great feature.

**Comment by euantorano** [comment]
So how do we want to handle remote avatars? IMO, the easiest thing to do is simply default to the default avatar and show a notice in the user CP as @Devilshakerz suggested.

**Comment by WildcardSearch** [comment]
It seems to me that the issue should thought of on two separate planes.

Expected behavior for disabling something is that users experience the inability to use that particular functionality both in practice and in terms of receiving those options. I think removing the remote avatar's link and replacing it with the default avatar is overstepping the bounds of 'disable'.

The disabling of functionality should happen conditionally in the affected code. More work, I know, but it would be appropriate, in my opinion.

The resetting of all remote avatars to the default seems like it should be a separate tool.

**Comment by euantorano** [comment]
Well, I'm about to submit a PR in a couple of minutes, we can change that based upon feedback from testing I guess :smile:

**Comment by WildcardSearch** [comment]
No worries.
