### ISSUE TITLE
Help Documents HTML not parsed in misc.php?action=helpresults

### ISSUE THREAD

**Issue by Ben-Conway** [mybb/mybb#2428]
I have some help documents which use HTML and inline CSS to make them look pretty.

If you use the search feature located within misc.php?action=help the search results will display the raw HTML/CSS like so:

Original thread: [Help Documents HTML not parsed in misc.php?action=helpresults](http://community.mybb.com/thread-192089.html)

**Comment by Destroy666x** [comment]
>  strip_tags() doesn't seem to affect <style> and <script> tags. This problem may be present in other places that use that function

**Comment by Matslom** [comment]
Is [there](https://github.com/mybb/mybb/blob/feature/misc.php#L336) reason to using parser when we use strip_tags?

**Comment by Shade-** [comment]
Yes, because the string is [chunked to 350 chars](https://github.com/mybb/mybb/blob/feature/misc.php#L340) a few lines afterwards. If you don't `strip_tags()`, a closing HTML tag (like `</div>`) might be removed leading to various styling issues.

I think this can be addressed by creating a custom `my_strip_tags()` function which handles <style> and <script> tags, either by using a regex or PHP's DOMDocument. Regexes are faster, but they are not very precise when handling HTML markup, while DOMDocument has been built appositely for HTML/XML handling so it's way more accurate, but it might unnecessarily lead to performance lacks for a relatively unimportant purpose.

**Comment by Matslom** [comment]
I know this, but why we call message parser in this place if we anyway use `strip_tags()` function?
Anyway, I checked all `strip_tags()` use and this is only place which need fix. Using parser or not, doesn't matter.
>I think this can be addressed by creating a custom my_strip_tags()

Yea, I did this. I used regex for catch and remove `<script>` and `<style>`. I will send PR shortly.
