### ISSUE TITLE
Host check code doesn't work anymore

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#2445]
https://github.com/Devilshakerz/mybb/blob/4b11a11b4f5c1fea22b622bf8e5f8f073e625a4f/inc/functions_serverstats.php#L215

That site doesn't seem to work that way anymore. Also, replacing `www.` was never fully proper because the URL can be something like `http://thewww.com`

**Comment by JoshHarmon** [comment]
New URL is http://www.whoishostingthis.com/?q={$DOMAIN}

New pattern is, from what I can tell: 

`{$DOMAIN}</span> is hosted by <span class="normal blue"><a href="/go/{$HOST_SLUG}/?track=WIHT-SiteProfile" target="_blank">{$HOST_NAME_PRETTY}`

So, a WIHT search of hostgator.com would return the HTML

`
hostgator.com</span> is hosted by <span class="normal blue"><a href="/go/hostgator/?track=WIHT-SiteProfile" target="_blank">HostGator
`

**Comment by JN-Jones** [comment]
@JoshHarmon @mybb/developers Has anybody tried to look at this?

**Comment by JoshHarmon** [comment]
Haven't taken a very comprehensive look at it, but the pattern I posted above should be sufficient for building a new regex. I don't know what the failure/unknown pattern looks like though.

**Comment by nsuchy** [comment]
"Update: It looks like they fetch the data via JS now, so I'm not sure if we can satisfactorily pull the data from this site anymore."
Have you considered scraping the data? There's no longer an API but the selector "`#site > div > div > div.pure-u-1.pure-u-lg-1-3.cloudflare > div > div:nth-child(3) > ul > li:nth-child(1) > a`" should make this pretty straight forward.

**Comment by effone** [comment]
Seems like their API is down.
Why don't we just use PHP's `gethostname();` ?

I know it returns the hosting server name in place of the company name but that info should be enough, right?
even the nearest alternative `http://who-hosts.com` returns the same thing instead of actual hosting company name. Moreover; I find it more accurate than trying to get the company name.
`gethostname();` returned me my actual hosting server name which I know correct.
`http://who-hosts.com` returned the polite version of the same data.
whoishostingthis has given me a name which I am never aware of as my hosting provider (though the nameservers were correct).

**Comment by euantorano** [comment]
I question why we really need this information in the first place realistically.

**Comment by effone** [comment]
@euantorano right. On an other note this may appear to some audience as grabbing private data (host / server name) for no reason in this day of dealing with data privacy.

**Comment by euantorano** [comment]
Yes, which is why I think we only need PHP version/extensions and database version. Any other data is useless to us.

**Comment by effone** [comment]
So shall I make a PR dropping that part?

**Comment by euantorano** [comment]
Sounds good to me!

**Comment by nsuchy** [comment]
<img width="1280" alt="screen shot 2018-06-06 at 3 30 11 pm" src="https://user-images.githubusercontent.com/8227641/41060744-88954f46-699e-11e8-8e36-8cd67f8f2496.png">
Clippy told me what to do - try adding `<?php` on line 1.
