### ISSUE TITLE
Delayed moderation - missing lang string for time

### ISSUE THREAD

**Issue by Cu8eeeR** [mybb/mybb#2497]
https://community.mybb.com/thread-203431.html

Anyway. the lang string is here... am I right? 
https://github.com/mybb/mybb/blob/feature/install/resources/mybb_theme.xml#L8010

**Comment by JN-Jones** [comment]
The language string is only defined in `modcp.lang.php` which isn't loaded in `moderation.php`.

Anyways I'd prefer if you don't create issues for reports which hasn't been looked at by a team member. It's a lot easier for us if we can sort them first and push them using our tools instead of cleaning up behind you.

**Comment by Cu8eR** [comment]
@JN-Jones - there are over 3 pages of bugs report - many of then from 2014 - it would be nice if you can push/close/reject them... no offence, just my 0.02$
