### ISSUE TITLE
Update SCEditor

### ISSUE THREAD

**Issue by JN-Jones** [mybb/mybb#2542]
As mentioned elsewhere we should update SCEditor in 1.8.10. This will fix the following issues:

* #2045
* Probably #2112 
* #1674 
* Proper base for #2440 (may not be in the next version but the one after that)
* [Forum report](https://community.mybb.com/thread-173071.html) (https://github.com/samclarke/SCEditor/issues/545)

**Comment by MyBB-Andro** [comment]
Though it is bit offtopic, since we are making changes to the editor would to mention this. Would like to see as first option under the Insert a video dropdown. It is widely used now a days, so good to have it pre-selected as default Video Type. Ordering by popularity would be better than alphabetically for this area, IMHO.

**Comment by Cu8eeeR** [comment]
@JN-Jones - I agree, it would be nice to update all 3rd packages in 1.8.10 release

**Comment by martec** [comment]
?
but 2.0 not released yet https://github.com/samclarke/SCEditor/milestone/8

**Comment by Cu8eeeR** [comment]
@samclarke is working on v2.0 release, so it shouldnt take long. SCeditor is a drawback in MyBB 1.8, with new release it should be better :)

**Comment by Ben-MyBB** [comment]
@euantorano @mybb/sqa Can we get this done ASAP? This would fix a lot of issues we have been having since very early into 1.8 with Sam going missing

**Comment by WildcardSearch** [comment]
@Ben-MyBB 2.0 isn't finished yet: https://github.com/samclarke/SCEditor/milestone/8

**Comment by Eldenroot** [comment]
https://github.com/samclarke/SCEditor/issues/580

There should be a new version soon! ;)

**Comment by Eldenroot** [comment]
SCeditor v2.0.0 is available... changelog is quite long, I hope it will be better than now

**Comment by martec** [comment]
some issues reported by mybb users won't will fixed with 2.1 unfortunately.
we need wait for 2.2. https://github.com/samclarke/SCEditor/milestone/10
many things were just postponed to 2.2

bugs that only will fixed with 2.2
https://github.com/mybb/mybb/issues/2217
https://github.com/mybb/mybb/issues/1674
https://github.com/samclarke/SCEditor/issues/545
