### ISSUE TITLE
Change to SMTP mail composition to comply with standards

### ISSUE THREAD

**Issue by nmalcolm** [mybb/mybb#257]
> **Problem:**  
> ## When a user writes an Email (PM) to another user, the mail header is constructed in this manner now (only the important lines):  
> 
> Return-Path: <fromemail>  
> To: <toemail>  
> From: <fromemail>  
> ## Reply-To: <fromemail>  
> 
> This (often) results in the mail server sending an error : <ins>_"The mail server does not understand the RCPT TO command. Reason: 553 5.7.1. Sender address rejected: not owned by user XXXXXX."_</ins>  
> As it seems, the attempt to send an email from [user@xxx.com](mailto:user@xxx.com) from the mailserver yyy.com is seen as a potential abuse and is rejected.
> ## **The mail should therefor be constructed (correctly) in this manner:**  
> 
> Return-Path: <Mybb_name> <Mybb_returnmail/adminmail>  
> To: <toname> <toemail>  
> From: <Mybb_name <Mybb_adminmail>  
> ## Reply-To: <fromname> <fromemail>  
> 
> **This scheme should be mandatory for ALL emails sent by the system.**  
> The names in front of the email adresses are required to avoid confusion for mail programs (e.g. mail programs like to use the "from name" when replying to a message when the "reply-to name" is empty (despite of the email).

Original report: http://dev.mybb.com/issues/1720
Reporter: Yuri Taillandier
Status: New

**Comment by Sama34** [comment]
I suppose we can check if the server is respecting the SPF policy before sending a e-mail. Or add a new setting if that is not possible.

**Comment by NotoriousPyro** [comment]
![image](https://cloud.githubusercontent.com/assets/706132/8344077/3814d7b0-1ad4-11e5-92ba-8dd76786689b.png)

Example test email sent by myself to myself using the board. The from field is now filled correctly and the reply-to is also filled with the user's email.

Not sure if this breaks anything though, so be warned.

**Comment by Evenprime** [comment]
I don't think it should be necessary to check if the domain that is used in the "from"-field uses SPF/is protected by DMARC. It is the responsibility of the administrator to use a forum reply-to adress that he/she has control over and therefore can set the correct SPF entries for that domain.

The only situation that I can think of where the from adress is not the forum adress, is the sending of mails from users to users (the initial reason for this issue report). This case should be fixed by passing the correct parameters to the mailing method. The from field should end up being the same adress that is used for all types of forum notifications, the "reply-to" adress should be that of the user that is sending the mail.

Anything beyond that (proper spf records for that "from" adress etc.) should not be the problem or focus of the forum software itself.

**Comment by kawaii** [comment]
Any word on this being fixed in 1.8.7? It's fairly crippling and means that my forum can't send ANY mail whatsoever due to having a correctly configured mail server... :(

**Comment by NotoriousPyro** [comment]
Can't you use phpmail until fixed?

**Comment by NotoriousPyro** [comment]
Or sendmail, rather.

**Comment by andrewjs18** [comment]
I had some mail setting issues when switching from php mail to smtp mail.  I'm using zoho for email now.

when I set up all of the SMTP settings in the admin cp, I was using the zoho super user username & password.  once I tested email generated from my forum, I was seeing this in the system mail logs: The mail server does not understand the MAIL FROM command. Reason: N/A

I'm not sure why I thought of this, but I changed the SMTP username & password so the username was the same as the admin email set up in the site details.  in other words, the admin email in site details was me@me.com and the username in the smtp mail settings was me@me.com.  only after then did emails start flowing properly.

another problem I ran into is emails from contact.php were not being sent out.  there was no error being logged.  I made the following patch, at the direction of @Devilshakerz to the contact.php file. 

I changed this:
my_mail($contactemail, $subject, $message, $mybb->input['email']);

to this:
my_mail($contactemail, $subject, $message, $mybb->settings['adminemail']);
