### ISSUE TITLE
User who is member of group that moderates certain (not all) furums is not recog...

### ISSUE THREAD

**Issue by nmalcolm** [mybb/mybb#259]
> Funcion is_operator($fid,$uid) in source file inc/functions.php returns false when called for users that are member of a group that moderates certain forums. This becomes clear when such a user does a search, then the header moderater column for "checkall" is missing in the table of thread resulds, and also in the thread results lines for threads of forums that are not moderated by his group is missing. I found out that the function is called as is_operator() or is_operator(0,$uid) retuns an erroneous result.  
> I have made a fix that works, which is attached

Original report: http://dev.mybb.com/issues/1700
Reporter: Ad Bakker
Status: New

**Comment by Destroy666x** [comment]
I don't understand this issue, does anyone @mybb/developers @mybb/sqa ? I think he meant that `is_moderator()` somehow doesn't consider all moderators if the first parameter equals 0, but I don't know how this "somehow" is possible since they're read directly from the cache: https://github.com/mybb/mybb/blob/feature/inc/functions.php#L1717

I think this can be rejected.
