### ISSUE TITLE
Double recipients with private messages

### ISSUE THREAD

**Issue by mastum** [mybb/mybb#2659]
How to reproduce with MyBB 1.8.10 default theme and language.

Write a private message to three or more members, one member receives and read the message and do Reply All, now if the member click on "preview" recipients have doubled!

**Comment by Shade-** [comment]
I can confirm this.

**Comment by Shade-** [comment]
Apparently, this is caused by autocomplete.js. I have debugged the incoming inputs and it seems like the library duplicates usernames sent. We can easily strip out multiple usernames on the backend side, but it would not fix the issue which should be applied to the autocomplete library instead. I have not debugged the issue inside the library though so I do not know where it duplicates them.

**Comment by euantorano** [comment]
Yes, the backend should do deduplication. Would be good to fix it at both ends though.

**Comment by MaFeSa** [comment]
Hi, there is some hope of seeing this bug solved for 1.8.15?
Thanks

**Comment by euantorano** [comment]
We don’t have a patch submitted yet, so no I’m afraid not at the moment.
