### ISSUE TITLE
SQL error on install due to reserved word in MySQL 8.0.2

### ISSUE THREAD

**Issue by kawaii** [mybb/mybb#2921]
When installing MyBB 1.8.X using MySQL 8.0.2 or above they will receive the following SQL error:
![image](https://user-images.githubusercontent.com/12242877/33285819-5da03802-d3ab-11e7-99d7-d9c171dd6d98.png)
This is due to `groups` now being a reserved word. This can be remedied by ensuring that column names are always quoted in queries.

**Comment by fluxtion** [comment]
If nobody else is working on this, I'll fix it. Can it be done at the level of the database class methods (i.e. redirect all fields through function with an `explode()`, `implode()` sequence) or should it be fixed by searching for every instance of a db object and changing its parameters? Obviously the second is more time consuming and means coding conventions in future should force everyone to quote their column names but it avoids an extra function call per query.

I'm Elliott on Discord btw. Only just got around to actually doing something. :-)

**Comment by euantorano** [comment]
It would need to be fixed by altering any and every query using the reserved name unfortunately. Due to the word `groups` being used in quite a few places, it's not even as simple as running a find and replace unfortunately.

In the future, this will be handled by the query builder (once we get one implemented and queries rewritten to make use of it. For now though, somebody gets the tedious manual job of quoting every query 😢

**Comment by euantorano** [comment]
This issue needs further thought than in #2955 - the ` escape character is only valid for MySQL databases, not for PostgreSQL or SQLite. The column name escapes will have to be conditional on the DB engine, or done in the DB class itself.

**Comment by Ben-MyBB** [comment]
@euantorano thoughts on this for 1.8/1.9/1.10? I have yet to see any reports for this issue so doesn't seem a very high priority for 1.8 imo.

**Comment by euantorano** [comment]
As time wears on, this will become a bigger issue for sure. I'd like to take a look over the DB classes and see what we can do with them for 1.9, at the very least by implementing PDO for all engines and dropping older code (`mysql_*`, etc.). As part of that we could look at this issue hopefully.

**Comment by Gene64** [comment]
Any progress on this?
