### ISSUE TITLE
ModCP Permissions to view Reported Posts

### ISSUE THREAD

**Issue by kawaii** [mybb/mybb#2990]
Permissions don't work to see modcp reported posts if the permission group is secondary group.

From modcp.php:

Code:if(&#36;mybb-&gt;input['action'] == "reports")
{
    if(&#36;mybb-&gt;usergroup['canmanagereportedcontent'] == 0)
    {
        error_no_permission();
    }
So that has to be changed to reflect secondary group permissions.

Original thread: [ModCP Permissions to view Reported Posts](https://community.mybb.com/thread-215384.html)

**Comment by kawaii** [comment]
I've confirmed the issue on MyBB 1.8.14. Users with the 'registered' group as their primary and 'moderators' as a secondary will not have access to view the entire report center section of the ModCP, even if the moderators group is assigned to a specific forum as the description of the feature possibly suggests.

**Comment by labrocca** [comment]
btw just fixing the permission line for 

`	if($numreportedposts == 0 && $mybb->usergroup['issupermod'] != 1)
	{
		error($lang->you_cannot_view_reported_posts);
	}`

That doesn't fix an additional issue which allows for all the reported posts to display and then marked read.  So assume that has to be fixed and then to avoid tamper data the submit action should be checked too because it's not doing it now.

**Comment by labrocca** [comment]
An HF member has given me this fix. I have yet to test but the code appears right.  Would love for this to be fixed asap as it is a vital permission.

There are 2 issues with /modcp.php and how it handles reports for group moderators.

1.) Line 351: MyBB ONLY checks if user is a supermod. It SHOULD also check if user can manage reported posts.

Old Code:
`if($numreportedposts == 0 && $mybb->usergroup['issupermod'] != 1)`

New Code:
`if($numreportedposts == 0 && $mybb->usergroup['issupermod'] != 1 && $mybb->usergroup['canmanagereportedcontent'] != 1)`

The new code adds in the check if a user is not a supermod but can still handle reported posts.


2.) Line 61: MyBB does not filter reports properly for ADDITIONAL GROUPS that have moderator abilities. Currently MyBB only checks for the primary usergroup. This can easily be fixed by altering the query to check all usergroups instead of just the primary usergroup.

Old Code:
`$query = $db->simple_select("moderators", "*", "(id='{$mybb->user['uid']}' AND isgroup = '0') OR (id='{$mybb->user['usergroup']}' AND isgroup = '1')");`

New Code:
`$query = $db->simple_select("moderators", "*", "(id='{$mybb->user['uid']}' AND isgroup = '0') OR (id IN ({$mybb->usergroup['all_usergroups']}) AND isgroup = '1')");`

(Look right after the [i]OR[/i] for code change)

The new code changes looking for the primary usergroup to looking at all the usergroups a member is in. This allows additional groups to see (and handle) their own forum reports.

**Comment by euantorano** [comment]
@labrocca Any chance you could try the patch in https://github.com/mybb/mybb/pull/2999 - it appears to fix the problem from my limited testing.

**Comment by euantorano** [comment]
Also, note that point 1 is covered in the `if` block above the block you highlighted: https://github.com/mybb/mybb/blob/feature/modcp.php#L346-L349
