### ISSUE TITLE
User Pruning bug

### ISSUE THREAD

**Issue by nmalcolm** [mybb/mybb#307]
> When user pruning people with less than x posts, the user may in fact have the required amount of posts but they may not show up in the mybb_users postnum field due to the posts not counting in a certain forum, e.g. the "Testing" forum on MyBB.
> 
> An example would be pruning a user who has posted in the /me thread 50 times but no where else, maintaining a post count of 0. If the pruner would be run, they would be deleted.
> 
> I'm guessing this isn't intended, and probably should be looked into.

Original report: http://dev.mybb.com/issues/2139
Reporter: Paul H.
Status: Confirmed

**Comment by Sama34** [comment]
I'm not sure if we should check for soft-deleted/unapproved/drafts or simply count them all as I did in my PR.

**Comment by Destroy666x** [comment]
> soft-deleted/unapproved/drafts

I think they should be always excluded.

Also, what if the admin wants to consider only posts from forums which increase the post count and has set pruning only for that a while ago? That's why for backwards compatibility I think we should introduce another post pruning setting:
Title: `Count all posts?`
Desc: `If set to yes, posts from forums which don't increase users' post count will also be considered.`
Optionscode: `yesno`
Default: `0`/`no`

And execute the new query only if it's set to Yes.

**Comment by Sama34** [comment]
Then this wouldn't be a bug but an enhancement! Done.

**Comment by Sama34** [comment]
I agree it should be for soft-deleted post but not unapproved.. we need somebody else to draw the odds.

@mybb/developers @JN-Jones

**Comment by Sama34** [comment]
I have pushed directly.

e6853da2da3f70a12a4e7ea4235a31d64737b887

If that is it this can be closed.
