### ISSUE TITLE
Empty Email Address can result in PHP Warning on user validation

### ISSUE THREAD

**Issue by dvz** [mybb/mybb#3081]
The password validation in the `UserDataHandler::verify_password()` method can result in a _Empty needle_ PHP warning at https://github.com/mybb/mybb/blob/mybb_1815/inc/datahandlers/user.php#L191

The password is being checked before the email in [`UserDataHandler::validate_user()`](https://github.com/mybb/mybb/blob/mybb_1815/inc/datahandlers/user.php#L938)

**Comment by JordanMussi** [comment]
@effone [`strpos`](https://secure.php.net/manual/en/function.strpos.php) returns `0` if the needle is found in the first position of the haystack and `false` if the needle is not found at all. Hence the use of strict comparison in order to check that the needle was not found in the haystack.

The check here is correct as it is ensuring that the username nor the email address are located in the password and the password is not located in the username nor the email.
https://github.com/mybb/mybb/blob/a607821ffb46e1d3c1accfa5f415f78bafef038c/inc/datahandlers/user.php#L190-L192

---

I believe that the solution would be to make the call to `verify_email` before `verify_password` in [`validate_user`](https://github.com/mybb/mybb/blob/mybb_1815/inc/datahandlers/user.php#L938).
https://github.com/mybb/mybb/blob/a607821ffb46e1d3c1accfa5f415f78bafef038c/inc/datahandlers/user.php#L967-L978

**Comment by effone** [comment]
Okay I got it now...

**Comment by Sama34** [comment]
I wasn't able to reproduce so I don't understand how this will stop `$user['email']` from being an empty needle when `verify_email()` doesn't modify it at all.

**Comment by Shade-** [comment]
I have encountered this myself with a plugin of mines where I don't use any email to register users, and the immediate solution I found was to not declare any email key in the user array. However, I too can't see how this will solve the issue as 1) `verify_password()` doesn't modify `$user['email']` as @Sama34 pointed out and 2) it doesn't prevent `verify_email()` to run and check against an empty `$user['email']`, if provided.

**Comment by Sama34** [comment]
Did I miss something? Because I still can't see how this fixes the issue.

**Comment by euantorano** [comment]
You're right, this doesn't solve the issue after some mor testing. I'm re-opening the issue.

**Comment by Shade-** [comment]
I'd just add `!empty($user['email'])` to `verify_password()`'s `bad_password_security` condition. That'll prevent the warning, and empty emails will be then handled by `verify_email()`.
