### ISSUE TITLE
MyBB Registration Error

### ISSUE THREAD

**Issue by LubricantJam** [mybb/mybb#3270]
Screenshot of the error provided. Happens with CloudFlare protection on I think it's due to an ipv6 IP. 

https://cdn.discordapp.com/attachments/348881435983085569/459775155682672641/98f0db63e6ce6f0a1d55a8f361bbfba8-png.jpg

**Comment by AndreRl** [comment]
Doesn't look like a bug too me. Typically happens when MYSQL strict mode is on. Can't replicate this neither.

**Comment by Azareal** [comment]
Maybe it's a collation thing.

**Comment by fluxtion** [comment]
All `*_db_inserts.php` files set up the tables with a `regip` field theoretically large enough to hold any IPv6 address. Strict mode should have nothing to do with it.

As @Azareal said, it's almost certainly a collation issue. Any `utf8mb4` encoding should do. If that doesn't work, find a specific example of an IP address that doesn't work so we can at least try to replicate it.

(As a side-note, we should probably change the default MySQL collation to a `utf8mb4_x` if it's not already since that's the current recommendation)

**Comment by fluxtion** [comment]
All `*_db_inserts.php` files set up the tables with a `regip` field theoretically large enough to hold any IPv6 address. From what I understand, table collation in MySQL shouldn't matter since `VARBINARY` values are stored using a special agnostic binary collation regardless of table settings.

I don't think it's enough to say that it only "happens when MySQL strict mode is on" with the implication that it isn't a problem. That's the same as encouraging people to suppress all PHP warnings so that their code "doesn't have any obvious problems". It's lazy and sloppy. Users should be able to use strict mode to enforce best practices. And developers should be using strict/`E_ALL`/`-wall`/whatever on all their systems as a matter of routine.

If someone has managed to generate this error, it's worth investigating since it shouldn't be happening. `$_SERVER` should never be returning an IP that can't be compressed into a 16 bit binary field if the compression is done right. Having said that, without a specific example of an IP address that causes this error, it's impossible to replicate. @LubricantJam please post a specific example of an IP address if you want someone to investigate this. I'm happy to do it if you can provide the info.

**Comment by LewisTehMinerz** [comment]
I have this exact error. https://pastebin.com/fnC3uyFi

When the varbinary data is casted to a char(255), it is an IPv6 address. There's no compression.

**Comment by euantorano** [comment]
Do you have a copy of the original IPv6 address by any chance?

**Comment by LewisTehMinerz** [comment]
Sure do.

`2601:448:4200:6cb8:f976:a28d:8952:906c`

**Comment by euantorano** [comment]
I’m at work right now, but I’ll have a look into this tonight when I get home.

**Comment by LewisTehMinerz** [comment]
Alright. I've temporarily fixed it by setting the varbinary's length to 64, so it's less of a problem for us at the moment.

**Comment by euantorano** [comment]
I got a chance to have a very quick test while at work, though not against MyBB itself.

## MySQL built in `INET6_ATON`:

```sql
SELECT INET6_ATON('2601:448:4200:6cb8:f976:a28d:8952:906c') AS ip
```

Result:

```
0x2601044842006cb8f976a28d8952906c
```

**Length:**

```sql
SELECT OCTET_LENGTH(INET6_ATON('2601:448:4200:6cb8:f976:a28d:8952:906c')) AS length
```

Result:

```
16
```

[**SQL Fiddle**](http://sqlfiddle.com/#!9/6a7f8d/2)

## PHP `inet_pton`

```php
echo bin2hex(inet_pton('2601:448:4200:6cb8:f976:a28d:8952:906c'));
```

Result:

```
2601044842006cb8f976a28d8952906c
```

-------------------

The output that you provided contains a wildly different representation of the IP address to what Id expect to see based upon the above, so I wondered if the issue was our [fallback implementation](https://github.com/mybb/mybb/blob/1ded732f43d095a957767508fd653e0693090f11/inc/functions.php#L7716), but testing that it appears to be fine on my end, could you please try confirming it on your server?

```php
<?php

$version = phpversion();

echo "Version: {$version}<br/>";

if (!function_exists('inet_pton')) {
    die('inet_pton function doesn\'t exist');
}

function my_inet_pton($ip)
{
    $r = ip2long($ip);
    if($r !== false && $r != -1)
    {
        return pack('N', $r);
    }
    $delim_count = substr_count($ip, ':');
    if($delim_count < 1 || $delim_count > 7)
    {
        return false;
    }
    $r = explode(':', $ip);
    $rcount = count($r);
    if(($doub = array_search('', $r, 1)) !== false)
    {
        $length = (!$doub || $doub == $rcount - 1 ? 2 : 1);
        array_splice($r, $doub, $length, array_fill(0, 8 + $length - $rcount, 0));
    }
    $r = array_map('hexdec', $r);
    array_unshift($r, 'n*');
    $r = call_user_func_array('pack', $r);
    return $r;
}

$address = '2601:448:4200:6cb8:f976:a28d:8952:906c';

$builtIn = bin2hex(inet_pton($address));
$custom = bin2hex(my_inet_pton($address));

echo "Built in inet_pton: {$builtIn}<br/>";
echo "Custom inet_pton: {$custom}";
```

**Comment by LewisTehMinerz** [comment]
![](https://pantsu.review/b42b12.png)
I did just update the PHP version before doing this though, so here's the one from PHP 7:

![](https://pantsu.review/0f3a96.png)
Which appears to be.. the same?

**Comment by euantorano** [comment]
Damn, there goes that theory then. I'll need to go further down the rabbit hole.

**Comment by yuliu** [comment]
> ![](https://camo.githubusercontent.com/7e834a9839e1397598f019b9fa8681b7777c7f94/68747470733a2f2f70616e7473752e7265766965772f6234326231322e706e67)
> I did just update the PHP version before doing this though, so here's the one from PHP 7:
> 
> ![](https://camo.githubusercontent.com/f952ea1c2f90f8e5f446c8b9faf22adb7415cb88/68747470733a2f2f70616e7473752e7265766965772f3066336139362e706e67)
> Which appears to be.. the same?

If they're having the same result, then probably it's not MyBB core's issue.

> I have this exact error. https://pastebin.com/fnC3uyFi
> 
> When the varbinary data is casted to a char(255), it is an IPv6 address. There's no compression. I'm using CloudFlare as well.
> 
> cc @fluxtion

The address to be stored into database `323630313a3434383a343230303a366362383a663937363a613238643a383935323a39303663` is the string `2601:448:4200:6cb8:f976:a28d:8952:906c` converted to HEX. Yes it has colons in it, that seems not the way MyBB's fallback implementation or PHP built-in `inet_pton()` does where the colon `:` will be removed from an IPv6 address.

For MyBB's fallback:
- [`$r = explode(':', $ip);`](https://github.com/mybb/mybb/blob/1ded732f43d095a957767508fd653e0693090f11/inc/functions.php#L7745) results in `$r` with no colons.

For PHP built-in `inet_pton()`:
- ```var_dump(inet_pton('2601:448:4200:6cb8:f976:a28d:8952:906c'));```
   shows `inet_pton()`'s return for an IPv6 address is 16 bytes whereas `323630313a3434383a343230303a366362383a663937363a613238643a383935323a39303663` is 76 bytes. It's worth noting that `2601:448:4200:6cb8:f976:a28d:8952:906c` has 38 characters.
- ```var_dump(bin2hex(inet_pton('2601:448:4200:6cb8:f976:a28d:8952:906c')));```
  from this output you will see the PHP built-in one will return a presentation without colons as well.

So my guess to OP's problem cause could be a plugin may have altered relevant data fields, maybe `session::packedip` or `UserDataHandler::user_insert_data['regip']`.

---

A quick search on the community forum, the problem may be related to a plugin called Steam Login.
See this thread https://community.mybb.com/thread-221781.html?highlight=data+too+long+regip not sure if OP had posted in that thread too.

---

With a little further investigation, you'll find the real culprit here: https://github.com/floofytsuna/Steam-Login-MyBB-1.8/blob/1.8/inc/plugins/steamlogin.php#L458
