### ISSUE TITLE
Underflow when user attempts incorrect password

### ISSUE THREAD

**Issue by Krytic** [mybb/mybb#3293]
Discovered when trying to log into my community.mybb.com account.

It seems that when a user fails a log in more than x times and gets locked out for 15 minutes, there is some possibility for integer underflow with the timer. I am not sure what the necessary condition is to achieve this.

Proof:

![image](https://user-images.githubusercontent.com/12708480/42161008-666e95d0-7e4d-11e8-8cbb-9d96557ec2ab.png)

The timer keeps getting more negative.

(side note since I now cannot log in to my community.mybb.com account, if this is reversible can you revert it for me? :) )

**Comment by Shade-** [comment]
Hi, this has been already spotted and should have been fixed with https://github.com/mybb/mybb/pull/3292. The patch will be applied to the community forums shortly. In the meantime, you can clear your MyBB-related browser cookies.

Note that official releases are unaffected by this issue as it has been introduced in #3115.
