### ISSUE TITLE
Regression on PR #2812 - Force Custom profile fields on Admins & Mods

### ISSUE THREAD

**Issue by AndreRl** [mybb/mybb#3395]
I see no reason to keep #2812. Just because it was there before doesn't mean it should stay, it causes more trouble than not IMO. At this precise moment you can have a Custom profile field "Viewable to" setting set to "None" and that said custom profile field will still show for Admins and Moderators on the Profile. As it's an Administrator setting the "Viewable to" option to "None" (or not their own group), they clearly do not want to see the said field. Forcing them to see it is just silly, especially if it doesn't enhance security. 

If it stays as is, if admins & mods really do not want to see it they have to make a core edit. Without this change, if admins & mods really do not/or want to see it they only have to set the option to in the ACP.

**Comment by Eldenroot** [comment]
The easiest way is revert back to previous code.

**Comment by AndreRl** [comment]
Agreed @Eldenroot. If only we could @ the developers team to see what they say :P

**Comment by euantorano** [comment]
@mybb/developers

**Comment by AndreRl** [comment]
@mybb/developers yup

**Comment by euantorano** [comment]
Yeah, I think only team members can do it so we don't all get spammed.

**Comment by Sama34** [comment]
To bad I missed this. The original intention of that setting was to allow administrators to have more flexibility regarding display options. However, it was never intended for moderators (or users who can edit the field) to be affected by it, since, well, they can actually see the result anyways.

IMO this was a hierarchy issue, where it was decided to ignore the moderator level.

I would like to suggest to rever the setting and add a new one to meet other needs.

**Comment by Eldenroot** [comment]
Why not, this issue should be reopened and fixed properly.
