### ISSUE TITLE
Custom Profile Fields - Certain characters not escaped

### ISSUE THREAD

**Issue by AndreRl** [mybb/mybb#3397]
As title says, when you select in ACP -> Custom profile fields -> Add new profilefield -> field type "check boxes" and you add these values:

```
Text A
Text B
Text "C"
Text D
Text E 
```

Save custom profile field and go to UCP. In UCP select Text A, Text B, Text "C" and Text E and click to save button. Values are not saved, it is because "" is not escaped. We should add a note about that, error message or escape this type of char.

Original thread: [Custom profile fields - "" is not escaped, fields cannot be saved via UCP](https://community.mybb.com/thread-219059.html)

**Comment by AndreRl** [comment]
Just an FYI, I also noticed this when you use angle brackets (<>) so it's not all special characters.

**Comment by Eldenroot** [comment]
We just need to parse all special characters to html entities
http://php.net/manual/en/function.htmlspecialchars.php

**Comment by MinusPL** [comment]
Issue is actually pretty simple - all values are properly updated in database, also whole script can read them. Then what is preventing from displyaing? The fact, that every field is filled based on on non-escaped data names, what can cause that even if data is in db and is accessible by script it wont fill field, because script searches for non-escaped fields, when we have is database escaped ones.

Right now in usercp all customfields (profile fields) are handled without escaping strings. I mean ALL. Only textarea got htmlspecialchars_uni used in it, maybe it would be better idea to move htmlspecialchars_uni before checking what kind of field it is?

I'm currently doing some testing on it. Other fix is to apply htmlspecialchars_uni directly in checkboxes, but it's possible that this bug actually can happen in every single field. I'll test that and update here information on what I figured out.

**Comment by MinusPL** [comment]
Okay new comment to sum it all up:

Moving htmlspecialchars_uni before checking field type actually bugs it more, so I added htmlspecialchars_uni only to radio buttons and checkboxes and it seems to work properly now. Still need to look at registration is it going to save them, but I'll create pull request if everything is going to be working properly.
