### ISSUE TITLE
Change group issue

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#3433]
Hello,

There is a issue, when somebody (who have a group's leader managment permission) is trying to remove somebody from the group, it doesn't works. Works, when the person have "registered" as main group (and our group as dispayed for example). It's annoying and very uncomfortable to manage the users on the board.

I think they should be downgraded to "registered" group from (for example) "premium user" after, when they left the group.

It's possible to repair the issue?

Edit: If somebody have a other group than "premium user" as default, and he is in the group, there's no problem with removing him.

I just found here dragonexpert's opinion, that the UserCP group managment is not intend to change primary group:
https://community.mybb.com/thread-154254...pid1077029

I really need the function on my own, where the leader group can remove somebody, who have the group as primary (and it should moving the user to "registered" as default).

I'm trying to improve it by Group sort modification:
https://community.mybb.com/thread-206755...pid1256607

Original thread: [Change group issue](https://community.mybb.com/thread-206754.html)

**Comment by MinusPL** [comment]
I looked at this issue and noticed that leave_group function that is used to remove member from grup doesn't accept primary user group as one to remove. Right now it can only remove user from group if it is actually an additional group. It can be changed, but still thinking if it should automatically move user to registered primary group.

**Comment by linguisten** [comment]
It should accept all groups but the default group as primary groups to be left, so that one always falls back to the standard group

**Comment by MinusPL** [comment]
Yeah, but now someone has a problem where if user is member of groupA, and leader of groupA want to kick him from that group it's impossible to do so when your primary group is groupA. That's whole issue here. Forum still will consider that you have been kicked from this group and everything seems to be fine, but whole logic is that when you have it as primary one forum will set that group as your display group and that makes it impossible to kick you from groupA, because forum uses this group as your default one - basically you can't kick someone from groupA, because forum thinks that it is his ONLY group. Additional ones are terated as if they have never existed in that one moment.

**Comment by MinusPL** [comment]
@Ben-MyBB can you look at what I said above? I can create fix for this in few hours, but currently I have doubts if it should be changes the way I'm thinking of.
Basically - if primary user group is one that user is being kicked off it will automatically change primary user group to registered. Please reply, because I don't want to create something that could make things worse.

**Comment by Ben-MyBB** [comment]
@euantorano @WildcardSearch @dvz any thoughts on the above?

**Comment by WildcardSearch** [comment]
> There's no way that someone has changed his primary group by himself. To change user primary group you need to change it in ACP.

@MinusPL I think this quote sums it up for me.

If a user's primary group has been modified, they can't very well leave that group.

The original post indicates that mods/group leaders couldn't remove these users from the group because it was set as their primary group. **That is expected behavior.** If you want them to be able to remove those users, set their primary group to something else `(eg. registered`) and use the display group if you want to display those users as other than their primary group.

**Comment by MinusPL** [comment]
Yeah, I can only suggest adding notification about this situation when people want to remove someone from group A and this someone has it set as primary usergroup.

Another approach is for people to just understand that if they want to just let people join/leave groups (or kick/add for group leaders) it is required to have these groups as additional ones only.

**Comment by Ben-MyBB** [comment]
Related: #3894 for which a PR has been opened for a fix so closing this.
