### ISSUE TITLE
1.8.20 sceditor font-size change bug

### ISSUE THREAD

**Issue by kikelkik** [mybb/mybb#3591]
Hey,
since I updated MyBB to version 1.8.20 there is a display bug in the sceditor.

Steps to reproduce:
1. Write some words
2. mark one word and pick any color for font coloring
3. change font-size of the marked word
--> Font-size will be changed but the color switches back to black until I refresh the display by clicking "view source code" twice.

**Comment by MinusPL** [comment]
I wasn't able to reproduce your issue. Please make sure that you have checked your templates and if all files that were changed in MyBB 1.8.20 are correct. I've tried on clean instal of MyBB 1.8.20. If you can, please check on fresh install of MyBB if this issue exists. If issue doesn't occurs on fresh install then you should ask for support on official community forum at mybb.com.

**Comment by Eldenroot** [comment]
In my opinion would be better to implement SCeditor 2.0 in next release (v1.8.21) and do not waste time with fixing these kind of bugs in version 1.5.2 :(

I am not sure how difficult it could be but it could solve many issues and bring newer editor to MyBB. 

P.S. I have been using CKeditor (Rin editor) for years, much better!

**Comment by MinusPL** [comment]
@Eldenroot yeah CKEditor is better option, SCEditor is somewhat outdated and limited.
But as Euan somewhere noted it's not a really good idea to completely change editor just because of that.
He said that with 1.8.21 it is planned to update SCEditor to 2.1 and jQuery to the newest possible version.
I won't try to find what causes that issue much more, because I just went through all code again and again and found nothing but code that should work properly. As I noted in my thread - it depends on which browser you use to see more and more random and weird issues with SCEditor.
