### ISSUE TITLE
UI inconsistency: moving threads from forum view vs topic view

### ISSUE THREAD

**Issue by effone** [mybb/mybb#3632]
Reporting as requested here.

Inline Moderation ("forum view") allows to move topic(s), only.

Moderation Options ("topic view") allows to move/copy/move with redirects

As far as I understand, all 3 options should really be available in either case.

Original thread: [UI inconsistency: moving threads from forum view vs topic view](https://community.mybb.com/thread-222449.html)

**Comment by Eldenroot** [comment]
Good point, I was always curious why it is that inconsistent

**Comment by callumthomson** [comment]
Nobody discussed this issue for a while so I've created a pull request.

Note:

- In my pull request I also created a new hook `moderation_do_multimovethreads`, as there wasn't one already.
- Instead of modifying `Moderation::move_threads`, I've iterated over `Moderation::move_thread`, and unless there is a good reason to have both methods, it seems smart to remove `move_threads`, to avoid repeating code and, the method is weaker anyway as it does not support redirects / copying.
