### ISSUE TITLE
PM search - incorrect folder

### ISSUE THREAD

**Issue by effone** [mybb/mybb#3666]
When you search PMs, incorrect folders are displayed. It seems it reports "Unread" for all messages in "Inbox".

Original thread: [PM search - incorrect folder](https://community.mybb.com/thread-222668.html)

**Comment by MinusPL** [comment]
Almost fixed that. Need to test it more and will create PR soon.

**Comment by effone** [comment]
@MinusPL pardon me but the changes don't appear right to me.
Let me make you clear about few points.
- The old folder value is maintained in database (to support existing data before changes). So there is no chance `folder` can be `0`. 
- Only the folder structure is modified for representation purpose. So, folder `0` is `Inbox` and folder `1` is `Unread` its a wrong concept. For both cases its `1`. Still for safeside you can query the value with `< 2`.
- At runtime the `fid` is set to `0` based on folder value < 2 as inbox and all the messages not having `readtime` and / or status `0` considered as unread.
- We don't need to display the message in `unread` folder at all. Its not even a folder in practical, its more like a status filter.

**Comment by MinusPL** [comment]
@effone 
So basically folders are left in db only because these were used in earlier system?
I think that this whole private message system is in need of changes considering how it is currently working. And this leftover value made me think it was causing this issue.
I think I saw somewhere on community forum that there's plan to change it or update it for 1.9 or 1.10.
For now your way of fixing this issue is good.
Tthanks for your reply, and thanks for your work.

**Comment by effone** [comment]
Messaging system is expected to be revamped in future. Yes.
We have all enthusiasm left yet to carry MyBB with its all glory. Cross finger.
