### ISSUE TITLE
hardcoded SID causes missing CSS when exporting PMs in HTML, after upgrading

### ISSUE THREAD

**Issue by JWhyFR** [mybb/mybb#3779]
Hello,

I open this issue following noyle's advice in MyBB Community Forums : https://community.mybb.com/thread-224378.html 

In _private.php_ , the following code is supposed to retrieve the global.css stylesheet :
`$query = $db->simple_select("themestylesheets", "stylesheet", "sid = '1'", array('limit' => 1)); `

However, after upgrading myBB (from 1.8.14 to 1.8.20 or 1.8.21), this SID is not in the _themestylesheets_ table anymore because of stylesheets updates (delete+insert, with an auto_increment PK)

As a result, the "Export Private Messages" feature is not working as expected (when selecting HTML format) : CSS is not applied.

More info / screenshots [in the original thread](https://community.mybb.com/thread-224378.html)

Thanks,

JY.

**Comment by yuliu** [comment]
It's a little bit complicated to track how those CSS are deleted and re-inserted. But for sure following CSS are re-imported in each version upgrades if `revert_all_themes` is set to zero in the upgrade script:
```
global.css
usercp.css
modcp.css
star_ratings.css
showthread.css
thread_status.css
css3.css
```

If `revert_all_themes` is not set to zero, the whole `themestylesheets` table is dropped then created then CSS being imported.

The function used to import CSS in a theme file is `import_theme_xml()` in `./admin/inc/functions_themes.php`, following which one can read about the relevant actions [here](https://github.com/mybb/mybb/blob/fda816dfab9d93c24f95ba76a925ac6bde72b3c4/admin/inc/functions_themes.php#L219-L225) with calling parameter `$options` inputted [here](https://github.com/mybb/mybb/blob/fda816dfab9d93c24f95ba76a925ac6bde72b3c4/install/upgrade.php#L487).

The easiest way to reproduce the problem is to install a new mybb, run an upgrade script, and watch what happens to the `themestylesheets` table. BTW, the upgrade script for 1.8.21 to future version 1.8.22 breaks as it forgets some output work to do. I'd like to just submit a PR without creating an issue since it's really not a 1.8.21's bug.

**Comment by Eldenroot** [comment]
@yuliu - will you post a PR?

**Comment by yuliu** [comment]
I've had a fix of it in a little bigger PR #3782. Should I post a separated PR all by itself?

**Comment by yuliu** [comment]
PM export function is likely striped from 1.9, though I'm not very sure. We may need to fix this issue in .27, now or never.

**Comment by euantorano** [comment]
I agree, it's a simple fix and good for quality of life.

PM export ill be staying in 1.9, but may change in the future if we make drastic changes to private messaging (e.g. threaded conversations).
