### ISSUE TITLE
Missing colon

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#3796]
editpost and newthread templates.

Missing colon by Subject.

Original thread: [Missing colon](https://community.mybb.com/thread-223880.html)

**Comment by Eldenroot** [comment]
So move colon from language files to template or ftom template to lang file??? @Ben-MyBB

**Comment by yuliu** [comment]
I vote for language file. Colon can be different in languages. Please refer to https://en.wikipedia.org/wiki/Colon_(punctuation)#Usage_in_other_languages .

I also suggest to move literal space ` ` and `&nbsp;` things to language files rather than templates rather than in scripts. See https://en.wikipedia.org/wiki/Space_(punctuation)#Use_in_natural_languages for usages with no spaces.

**Comment by euantorano** [comment]
I would also vote language files - existing lang files (if any) should be updated.

**Comment by yuliu** [comment]
It's worth nothing that Ashley1's [comment](https://community.mybb.com/thread-223880-post-1332893.html#pid1332893) also makes sense on **whether or not** to use a colon.

If we really need to use a colon or a comma (in some situation, eg. listing moderators, alternative is separator like `|` or by CSS), I would like to put it in the language files since it's really language-specific rather than template-specific.

**Comment by Eldenroot** [comment]
OK, so that doesnt many sense to move ":" into lang files - in Ashley's comment, he wanna to remove them completely...

**Comment by yuliu** [comment]
@Eldenroot yes, but currently it's best to move _spaces_, _commas_, _colon_, etc., to language files, to maintain the consistency in this MyBB version.

Anyway, for future version, such as 1.9 or 1.10, language specific formatting characters (_spaces_, _commas_, _colon_, etc.) should be moved to lang files. And further, whether or not to use _colon_, or even for _period_, it should be working with theme to match each other.
