### ISSUE TITLE
Post merge doesn't do check on video/image count

### ISSUE THREAD

**Issue by effone** [mybb/mybb#3804]
Well, it's pretty obvious through this thread: https://community.mybb.com/thread-224651.html , which breaks the intention of limiting maximum videos/images per post if post merge is available.

Original thread: [Post merge doesn't do check on video/image count](https://community.mybb.com/thread-224655.html)

**Comment by dvz** [comment]
There are more problems with the logic around post merges and limits, and how mergeable posts are expected to be separate, but treated as a single one. E.g.:
 - it's not possible to edit the resulting posts that exceed some limits without removing some items (videos, images, attachments, etc.),
 - if the limits are verified on the resulting posts, like currently proposed in #4214, it may be impossible to post more items within _Post Merge Time_, which may be unexpected.

**Comment by Xazin** [comment]
> * if the limits are verified on the resulting posts, like currently proposed in #4214, it may be impossible to post more items within _Post Merge Time_, which may be unexpected.

What if we make it so it doesn't merge when it can't, but instead creates a new post separately. That way it still limits individual posts to the settings imposed from admincp, but it also enables people to post as long as their post is outside the flood time.

Note: I re-worked the proposal a bit and introduced changes to _insert_post()_ instead of _validate_post()_
