### ISSUE TITLE
Posting a comment on a thread doesn't remove the comment from the box

### ISSUE THREAD

**Issue by Burday** [mybb/mybb#3807]
Expected outcome: You write your comment, post it and as it gets posted, your comment gets cleared from the "Type your reply here" box.
Actual outcome: That never happens. The message is posted and it remains in the box. 

It isn't a major bug, but it could lead to people being confused and double posting the reply.

**Comment by effone** [comment]
Where is `Type your reply here` box? If you are referring to Quick Reply then sadly I failed to reproduce.

**Comment by Burday** [comment]
This is the box I'm talking about. https://i.imgur.com/hv4eVW9.png

Sorry I can't give much info, I don't own a forum on your platform but I'm reporting this issue from my experience with a forum using your platform

**Comment by effone** [comment]
Well, thats the Quick Reply box and yes it definitely removes the post content form there after posting successfully.

It is possible that the site where you have faced this issue is having some javascript errors. 

It appears to be a wrong report and I am closing the issue until someone flags with reproduction steps and some valid proof of the existance of the  issue.
