### ISSUE TITLE
Header no longer displays red alert join requests to groupleaders

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#3818]
Hello there,

I've noticed that earlier this year after an update, the header no longer showed pending group requests for groupleaders. It used to be a red alert message. Here's a picture of the header on the forums:

Here's the header template:

A few plugins are actively used -- but none I recall being modified/added when the functionality went away. Like System, Username Changes limit and history, edit history logs, shoutbox, automedia, admin user assumption.

I found this prior service request, which lead me to the post the header pictures above. 

Any ideas would certainly be helpful and appreciated to get this feature working again.

Thank you!

Original thread: [Header no longer displays red alert join requests to groupleaders](https://community.mybb.com/thread-224958.html)

**Comment by yuliu** [comment]
Group join request check for group joinablility is pulled in #3118, committed in https://github.com/mybb/mybb/commit/2c435663726ae035babc7dd676459eb0356049f9#diff-89024b9d05bdf5fd4144014492cc7caf . But there's no such `joinable` in group's properties.

v1.9 doesn't have this check yet. I think it needs to be discussed whether or not this check is needed.

#3026 says there's no need to show a notification of group join request if the group doesn't accept join request. But if there's any join request in the database, the requests should just have been submitted before the group closes its join acceptance, meaning that the join requests are valid. Or, if we view these join requests as invalid ones, we should also remove them from the database table `joinrequests`, not only just hide them from notifications.

Actually, the only data field that stores the on/off for group join request and invite is the `type` column in table `usergroups` ([the `type` values are only defined in AdminCP > Groups](https://github.com/mybb/mybb/blob/387849427d0c0c5458cc7414bb7689c794d90c18/admin/modules/user/groups.php#L840-L858) and [used in UserCP > `usergroups`](https://github.com/mybb/mybb/blob/387849427d0c0c5458cc7414bb7689c794d90c18/usercp.php#L3385-L3781)):
- `1`: system/built-in group
- &gt; `1`: groups are recognized as custom user groups
- `2`: custom group, no free join/leave
- `3`: custom group, free join/leave
- `4`: custom group, join needs moderation, free leave
- `5`: custom group, invite to join, free leave

**Comment by euantorano** [comment]
Ping @Shade-

**Comment by Ben-MyBB** [comment]
Note: possible fix https://community.mybb.com/thread-224958-post-1337274.html#pid1337274

@euantorano @yuliu

**Comment by yuliu** [comment]
Yes, it's a valid fix to this issue. But I'm just thinking whether we really should hide the notification here, if a group's join request is closed BUT there's any ongoing join request (must have been submitted before the group ends its join application).

Even the group closes its member join application (`type != 4`), thus the group management page under UserCP (`/usercp.php?action=usergroups`) won't show the link to list this group's join requests (`/managegroup.php?action=joinrequests&gid={$gid}`), but that link does permit access and join request processing.

Oh, I just find another logic issue here.

1. Let's set a group to open to join & require moderation. (`type == 4`)
2. A user submits a join request to this group.
3. The group leader or admin doesn't process this join request, and the group's been set to free to join without moderation or invitation. (`type == 3`)
4. **Here the issue**: the group leader **can't** see the link to the join requests processing page, and also the admin **can't** see any pending join requests in AdminCP, and the user **can't** join this group because the user will be notified with `You applied to join this group: ... ago`.

So, I think better not to check the group's `type` for the group's join requests that have already existed in database for front-end notification (this issue) and above-mentioned link in UserCP > Group Management and back-end highlighting of `(x outstanding join requests)` besides group name.

How do you think? @Ben-MyBB and other mybb developers.

**Comment by yuliu** [comment]
Wait a minute. My thought in previous reply is not so good, I think, it's just for temporarily solving this issue. A better version for that assumed circumstance should be:

- Drop the group's `type` check, display join request notification to group leaders in front-end and `(x outstanding join requests)` beside group name to admins in AdminCP > Users & Groups > Groups. Then the group leaders and admins can process the valid join request.
- If the group is set to no free join/leave (`type == 2`), existing join request is valid, no more work here.
- If the group is set to free join/leave (`type == 3`), for existing join request for this user, a join link should be placed beside such `You applied to join this group: ...` text, and upon submitting, MyBB should remove that existing join request from `joinrequests` table and then add this user to the group.
- If the group stays the same, join needs moderation, free leave (`type == 4`), no more work here.
- If the group is set to invite to join, free leave (`type == 5`), existing join requests are still valid, but current codes just mistakenly show join requests as join invites.

However, we still need a full solution that takes care of all possible scenarios.
