### ISSUE TITLE
Search - non-english characters are not counted to the search limit

### ISSUE THREAD

**Issue by Eldenroot** [mybb/mybb#3836]
My minimum search word lenght is set to 3 (Standard search type).

Anyway if you use any "non-english" character - iny my case "á", "é", "í", "ž" etc. (Czech language) it wont count as a character to the limit. So I get the error message that my phrase is too short. (noa vs noá, etc.)

![image](https://user-images.githubusercontent.com/778890/70235992-50eb7c80-1764-11ea-8363-3224ab07fc6e.png)

**Comment by Ben-MyBB** [comment]
@Eldenroot Can you create a PR for this?

**Comment by Eldenroot** [comment]
Sorry, do not how to properly fix it in a simple way. Maybe others who have more knowledge of coding? Thx!

**Comment by euantorano** [comment]
I'm looking into this. I wonder if it is related to #3937.

**Comment by JordanMussi** [comment]
https://github.com/mybb/mybb/blob/213da31cad08c643c834a6fad85f9b5027f8c426/inc/functions_search.php#L248-L256

Word less than or equal to the minimum word search length are removed using the regex `/(\b.{1,{$min_word_length}})(\s)|(\b.{1,{$min_word_length}}$)/`. When set to 3 this becomes `/(\b.{1,3})(\s)|(\b.{1,3}$)/`

Plugging in an example: https://regexr.com/53a0o
`a be note noté longer déveloper` after replacement becomes `  note not longer déveloper`
The [word boundary](https://www.regular-expressions.info/wordboundaries.html) `\b` matches between `not` and `é` causing it to be seen as a word shorter than the minimum length but for `déveloper` the `éveloper` is matched as the word but is long enough.

I think all that's needed is adding the unicode option to the matcher:
```
php > $str = 'a be note noté longer déveloper';
php > $out1 = preg_replace("/(\b.{1,3})(\s)|(\b.{1,3}$)/", '$2', $str);
php > $out2 = preg_replace("/(\b.{1,3})(\s)|(\b.{1,3}$)/u", '$2', $str);
php > echo $out1;
  note not longer déveloper
php > echo $out2;
  note noté longer déveloper
```

---

A side note to this issue is I find it weird how the replacement parameter is `'$2'` and not just `''`
```
php > $out3 = preg_replace("/(\b.{1,3})(\s)|(\b.{1,3}$)/u", '', $str);
php > echo $out3;
note noté longer déveloper
```

**Comment by JordanMussi** [comment]
@euantorano Yep I think it is the same cause

**Comment by euantorano** [comment]
Certainly seems it. #3942 may well kill two birds with one stone!

**Comment by Ben-MyBB** [comment]
@Eldenroot can you check if #3942 also resolved this issue?
