### ISSUE TITLE
Color not restarting after [/color]

### ISSUE THREAD

**Issue by tr1xy** [mybb/mybb#3968]
`[size=medium][color=crimson][i][b]Credits:[/b][/color] (Credits, Credits, Credits...)[/i][/size]`
Shouldn't that be

Credits `(in Crimson)`: (Credits, Credits, Credits) `(in default colour because of [/color])`

https://i.ibb.co/L0H18xd/image.png

**Comment by tr1xy** [comment]
Actually, the bug is present ONLY when previewing the message, the message after posting is OK.

**Comment by yuliu** [comment]
Will you try to correct the order of `[i]` and `[color]` in `[size=medium][color=crimson][i][b]Credits:[/b][/color] (Credits, Credits, Credits...)[/i][/size]`? See tags in bold:

[size=medium]**[color=crimson][i]**[b]Credits:[/b]**[/color]** (Credits, Credits, Credits...)**[/i]**[/size]

If you write something like above, spans of two tags are overlapped with each other but not nested, MyBB's parser will have a hard time in correctly parsing your message. So please try following:

`[size=medium][i][color=crimson][b]Credits:[/b][/color] (Credits, Credits, Credits...)[/i][/size]`

---

Honestly I don't know how this could happen. Even using the SCEditor in MyBB 1.8.22, it'll try to correct wrong nested/overlapped tags. For input `[size=medium][color=crimson][i][b]Credits:[/b][/color] (Credits, Credits, Credits...)[/i][/size]`, the editor will correct it as `[size=medium][color=crimson][i][b]Credits:[/b][/i][/color][i] (Credits, Credits, Credits...)[/i][/size]`

Will you elaborate more about your MyBB instance? For example the version it's on and if you have modified some core files.

**Comment by tr1xy** [comment]
> Will you try to correct the order of `[i]` and `[color]` in `[size=medium][color=crimson][i][b]Credits:[/b][/color] (Credits, Credits, Credits...)[/i][/size]`? See tags in bold:
> 
> [size=medium]**[color=crimson][i]**[b]Credits:[/b]**[/color]** (Credits, Credits, Credits...)**[/i]**[/size]
> 
> If you write something like above, spans of two tags are overlapped with each other but not nested, MyBB's parser will have a hard time in correctly parsing your message. So please try following:
> 
> `[size=medium][i][color=crimson][b]Credits:[/b][/color] (Credits, Credits, Credits...)[/i][/size]`
> 
> Honestly I don't know how this could happen. Even using the SCEditor in MyBB 1.8.22, it'll try to correct wrong nested/overlapped tags. For input `[size=medium][color=crimson][i][b]Credits:[/b][/color] (Credits, Credits, Credits...)[/i][/size]`, the editor will correct it as `[size=medium][color=crimson][i][b]Credits:[/b][/i][/color][i] (Credits, Credits, Credits...)[/i][/size]`
> 
> Will you elaborate more about your MyBB instance? For example the version it's on and if you have modified some core files.

I did not notice that and even if I did - I did not know that it matters, sorry...

Should I Close the issue? I switched from SMF so it's probably a little different as SMF does handle them iirc

**Comment by yuliu** [comment]
> I did not notice that and even if I did - I did not know that it matters, sorry...
> 
> Should I Close the issue? I switched from SMF so it's probably a little different as SMF does handle them iirc

I haven't looked into how SMF parses bbcode, but yeah you could be right that different forum software treats parser differently. I know one forum will simply replace bbcode as follows:
- `[font=XXX]` => `<span style="font-family: XXX">`
- `[color=#fff]` => `<span style="color: #fff">`
- `[i]` => `<span style="font-style: itatlic">`
- `[b]` => `<span style="font-weight: bold">`
- `[/font]` / `[/color]` / `[/i]` / `[/b]` => `</span>`

Then an input text just like yours that has overlapped or wrongly nested bbcode will be parsed into correct and valid HTML snippets.

I can't say which one is better: MyBB's is more strict but has low toleration on mal-formatted input, where as some other's seems robust in some circumstance but the way it allows mal-formatted input is just doing evil, IMO, and is probably bad for future upgrading or migration to other forum software providers.

It's OK for you to close this issue if you feel your problem is resolved. If you need further help or have further concerns or suggestions on this issue, please feel free to post them.

**Comment by tr1xy** [comment]
I can say that MyBB is better looking, not the core itself as I am noob for that but I can tell that MyBB themes are better and much more modern than SMF (+ ACP is **MUCH MUCH** more advanced)
