### ISSUE TITLE
Send thread uses non admin email to send mail

### ISSUE THREAD

**Issue by JordanMussi** [mybb/mybb#4048]
https://github.com/mybb/mybb/blob/76bd4568a4cbbf35b6b3922b8605e40809d7d6d2/sendthread.php#L201-L215

The user's email shouldn't be used since it is not owned by the forum. The admin email should be used instead with the user's email as the return address (as it currently is).

After a quick search this is the only place where `my_mail` is called with an email address that isn't the `adminemail` setting.

**Comment by yuliu** [comment]
Makes sense. It also makes sense that the email is sent by such user that the email is truly sent by this user and the forum is just sending it.

Or neither makes sense.

I don't think it needs fixing.

Current MyBB's mailing approach doesn't distinguish envelope senders and letter senders so well:
- For PHP mail the envelope sender can be set via additional parameters `-fmy_mail_from@example.com`
https://github.com/mybb/mybb/blob/9feef312dc22abef36dcc1ddb1a703e66d9c2fe1/inc/mailhandlers/php.php#L69
- For SMTP the envelope sender is probably represented by the SMTP authentication user and MyBB doesn't have settings for it. I guess there's some way to set the envelope sender but that might not be supported by all SMTP service providers or is restricted by some service providers.

**Comment by JordanMussi** [comment]
I don't think it is sensible to send from or mark a message as if it was sent from an address you don't own. The mail should be sent from the forum's mail just like every other message. If the intention of this code was to allow the recipient to reply to the sender then the return address does that. I don't see a reason why the from mail header should be set to the user's email. It feels likely that this would be caught in abuse/spam filters so if not for any other reason this should be changed for deliverability/reputation reasons.

**Comment by yuliu** [comment]
Yeah that's a good argument and I'll explain my thoughts.

> I don't think it is sensible to send from or mark a message as if it was sent from an address you don't own. The mail should be sent from the forum's mail just like every other message.

Usually mails sent _from_ / _by_ the forum are representing the forum itself. For example, the forum sends mails for account activation, password recovery, email/password change notifications to instruct or notify users with certain information; the forum sends mails for thread/forum subscription and PM notifications to notify users with new contents; and the forum sends mass mails by the admins to deliver certain news/promotion/etc. to users.

Whereas if a user send a thread to their friend, the mail itself doesn't represent the forum's opinion but the sender's and we can be sure that if a user send a thread to another, it's just this user's intention for spreading such information rather than the forum's idea.

> If the intention of this code was to allow the recipient to reply to the sender then the return address does that.

Yeah that's correct. No matter what the `From:` is for mails sent by users via this tool, the `Reply-To:` should be carefully set.

> I don't see a reason why the from mail header should be set to the user's email. It feels likely that this would be caught in abuse/spam filters so if not for any other reason this should be changed for deliverability/reputation reasons.

In either way of setting `From:` (the forum's email address or the user's), the feature of sending thread to friend can be abused, maybe by users using a fake or not his own email (email doesn't get validated/activated):
- If the forum's email was set for this tool, abusing this feature would probably result in the forum's email address being banned by some mail service.
- If the user's email was set, abusing this feature would probably mark the reputation of real mail delivering service (PHP mail / SMTP) lower.

Above circumstances may not be whole.


Although IMO the user's email should be responsible for the mails sent in this tool, I have concerns about using the user's email:
- We should make sure the email is used by them. If a forum require email activation, that'll be fine. Otherwise ideally, we may have to verify the email address.
- We should let the user know that their email address will be used.

That's why I said maybe neither makes sense, if the mailing isn't carefully configured or relevant policy isn't established.

**Comment by euantorano** [comment]
Note: some email servers require the From header to have the same email as the actual account and will error out when using a different email.

**Comment by yuliu** [comment]
> Note: some email servers require the From header to have the same email as the actual account and will error out when using a different email.

Yeah that's something we can't control and that's why I'd like to make MyBB's mailHandler more _hackable_, i.e., more plugin hooks to alter its behavior.

AFAIK, WordPress itself doesn't handle or force mail's `From:` to be a specific value, it only does what it thinks is right to fill the `From:` header field. And that's why some plugin will have an option like this:
```
Force From Name

If checked, the From Name setting above will be used for all emails, ignoring values set by other plugins.
```

Above setting is from [WP Mail SMTP](https://wordpress.org/plugins/wp-mail-smtp/), and its explanation:

> Popular email clients like Gmail, Yahoo, and Office 365 are in a constant battle with email spammers. One of the things they look at is if an email is originating from the location it claims to be originating from.
> If the proper authentication isn’t there, then emails either go in the SPAM folder or worst, don’t get delivered at all.
> This is a problem for a lot of WordPress sites because by default, WordPress uses the PHP mail function to send emails generated by WordPress or any contact form plugin like WPForms.
> The issue is that most WordPress hosting companies don’t have their servers properly configured for sending PHP emails.
> The combination of two causes your WordPress emails to not get delivered.
> ...
> For all options, you can specify the “from name” and “email address” for outgoing emails.

**Comment by JordanMussi** [comment]
> Usually mails sent _from_ / _by_ the forum are representing the forum itself.

I understand that point but this can simply be solved by doing the sort of hack I've seen some other software use: `From: "a.user@example.com" <forums@example.com>` or `From: "User (a.user@example.com)" <forums@example.com>`

> In either way of setting `From:` (the forum's email address or the user's), the feature of sending thread to friend can be abused, maybe by users using a fake or not his own email (email doesn't get validated/activated):

The default settings only allow registered users to use the send thread tool and that forces the email to be the user's email, only when a guest is using the tool does it use an email address specified in the form.

So with the default settings only registered users (who have activated via email) will be able to do it, so it has been confirmed the user controls their the email address.

> * If the forum's email was set for this tool, abusing this feature would probably result in the forum's email address being banned by some mail service.

This is why there are settings limiting number of send thread to friend per day and a flood time.

> * If the user's email was set, abusing this feature would probably mark the reputation of real mail delivering service (PHP mail / SMTP) lower.

Yes and so the reputation of the forum IP would be tainted for basically forging mails as if they are sent from an address they shouldn't send from.

> > Note: some email servers require the From header to have the same email as the actual account and will error out when using a different email.
> 
> Yeah that's something we can't control and that's why I'd like to make MyBB's mailHandler more _hackable_, i.e., more plugin hooks to alter its behavior.

This is precisely my point. The mail should be sent from the forum's address and it is something that can be controlled.

The mailhandler definitely needs improvement as there are various places where assumptions are made like in the example in the first post here where code outside the mailhandler is changing behaviour based on the handler type. What should happen is the `my_mail` function takes the from email and from name and does the logic inside. Anyway this is largely irrelevant as it would be better to bin it and replace with illuminate/mail or something else well tested.
