### ISSUE TITLE
Posts in unviewable threads appear in search

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#4083]
In my forum users recently noticed that they can see user's messages in removed thread when they search for their posts. I could confirm this happening even after I moved thread to another forum - to see if it's permission issue or not. It seems that post search feature doesn't check if that post is located in removed thread.

Original thread: [Post search doesn't check if thread is removed](https://community.mybb.com/thread-224436.html)

**Comment by Ben-MyBB** [comment]
While you can't actually open the thread from the results, you can actually view the posts in the thread in the search function.

**Comment by Eldenroot** [comment]
This one should have higher priority

**Comment by rajat315315** [comment]
Please allow me to resolve it. :)

**Comment by euantorano** [comment]
Please feel free to submit a PR 😀

**Comment by yuliu** [comment]
The root cause might be that `$search_data['visible']` doesn't get a value for users without relevant moderator privileges

https://github.com/mybb/mybb/blob/9feef312dc22abef36dcc1ddb1a703e66d9c2fe1/search.php#L1597-L1600

which results that `perform_search_mysql()` and `perform_search_mysql_ft()` won't have any restriction on thread/post visibility:

https://github.com/mybb/mybb/blob/mybb_1822/inc/functions_search.php#L1262-L1294
https://github.com/mybb/mybb/blob/mybb_1822/inc/functions_search.php#L1617-L1649


This is one only missing instance for `$search_data['visible']` in search.php for `$mybb->input['action'] == "do_search"`, and other actions in search.php should be checked too.

**Comment by rajat315315** [comment]
@yuliu the visibility part is again checked when showing the search results to user.

[https://github.com/mybb/mybb/blob/mybb_1822/search.php#L233-L278]
Here, the results are pruned according to visibility.

Although, you are correct that `$search['visible']` is missing, but finally in the above file, it gets checked.

I found out that the issue doesn't occur when `$search['resulttype'] == "threads"`, it occurs when `$search['resulttype'] == "posts"`, which is the default case when searching on the top right search bar.

[https://github.com/mybb/mybb/blob/mybb_1822/search.php#L234]

**Comment by rajat315315** [comment]
Also, is someone able to see something wrong with this if condition at
[https://github.com/mybb/mybb/blob/mybb_1822/search.php#L847-L849](https://github.com/mybb/mybb/blob/mybb_1822/search.php#L847-L849)

if `$thread['tid']` key doesn't exist in `$tids`, then `$tids[$thread['tid']]` should give error, am i correct?

**Comment by JordanMussi** [comment]
Sorry if I've stolen your thunder but I've submitted my own PR for this :/
