### ISSUE TITLE
Fix PHP 8.0 compatibility problems

### ISSUE THREAD

**Issue by dvz** [mybb/mybb#4138]
- [x] Various compatibility issues: #4095
- [x] Common _undefined_ errors — Admin CP: #4207
- [x] Common _undefined_ errors — front-end

**Comment by rajat315315** [comment]
Sorry for an off-topic comment but isn't 1.8.24 released a bit too early?
Couldn't understand the reason..

**Comment by euantorano** [comment]
@rajat315315 1.8.24 is a security release for a high risk security issue in SCEditor. It was made outside of normal schedule due to the security risk.

**Comment by dvz** [comment]
https://community.mybb.com/thread-232345.html

**Comment by yuliu** [comment]
Here are two more issues:

1. The language entry key `find` is different from that in language file `fine` in `./inc/languages/english/admin/tools_mailerrors.lang.php`.
2. The array `$log`'s key `find_from` and `find_to` in https://github.com/mybb/mybb/blob/8d1b606b4657f0a9f8f90c2f97cd6ed9d65379b2/admin/modules/tools/maillogs.php#L348 & https://github.com/mybb/mybb/blob/8d1b606b4657f0a9f8f90c2f97cd6ed9d65379b2/admin/modules/tools/maillogs.php#L367 respectively may not be defined. This might be a consequence of PR #4185 to relax mail log usage.

**Comment by dvz** [comment]
- [ ] https://github.com/mybb/mybb/blob/mybb_1827/inc/class_session.php#L60 `Undefined array key "HTTP_USER_AGENT"` [may be deferred]
- [x] https://github.com/mybb/mybb/blob/mybb_1827/inc/class_session.php#L555 `Undefined array key "uid"`
- [x] `$mybb->user` values initialized in `session::load_guest()` may need to be added to `session::load_spider()`

**Comment by Sama34** [comment]
> Warning [2] Undefined variable $redirect_url - Line: 11 - File: C:\xampp\htdocs\mybb\contact.php(305) : eval()'d code PHP 8.0.8 (WINNT)

**Comment by Sama34** [comment]
The following is nonsense (`$value === '0'`):
https://github.com/mybb/mybb/blob/ea30022ca1f4745b9c133b8ff131f3b78f374f52/admin/inc/class_form.php#L757

**Comment by Sama34** [comment]
> Warning [2] Undefined variable $comma - Line: 1 - File: C:\xampp\htdocs\mybb\forumdisplay.php(238) : eval()'d code PHP 8.0.8 (WINNT)

**Comment by Sama34** [comment]
> Warning [2] Trying to access array offset on value of type null - Line: 6032 - File: C:\xampp\htdocs\mybb\inc\functions.php PHP 8.0.8 (WINNT)
https://github.com/mybb/mybb/blob/ea30022ca1f4745b9c133b8ff131f3b78f374f52/inc/functions.php#L6032

**Comment by Sama34** [comment]
> Warning [2] Undefined property: MyLanguage::$permissions_user - Line: 2655 - File: C:\xampp\htdocs\mybb\admin\modules\forum\management.php PHP 8.0.8 (WINNT)

**Comment by Sama34** [comment]
> Warning [2] Undefined array key "colors" - Line: 1634 - File: C:\xampp\htdocs\mybb\admin\modules\style\themes.php PHP 8.0.8 (WINNT)

**Comment by Sama34** [comment]
https://github.com/mybb/mybb/blob/ea30022ca1f4745b9c133b8ff131f3b78f374f52/admin/index.php#L813

**Comment by Sama34** [comment]
> Warning [2] Undefined property: MyLanguage::$setting_group_newpoints_awards_shop - Line: 1933 - File: C:\xampp\htdocs\mybb\admin\modules\config\settings.php PHP 8.0.8 (WINNT)

https://github.com/mybb/mybb/blob/8cb31f99c1fa19c4c209cb50d37b27592b37b45d/admin/modules/config/settings.php#L1933

While at it :
https://github.com/mybb/mybb/blob/8cb31f99c1fa19c4c209cb50d37b27592b37b45d/admin/modules/config/settings.php#L1943

**Comment by dvz** [comment]
All known and recognized compatibility problems have been addressed; errors discovered after the next maintenance release will be tracked in a new Issue.

**Comment by yuliu** [comment]
Courtesy of #4305, [`libxml_disable_entity_loader()`](https://github.com/mybb/mybb/blob/f31100f85a45f4147998988f8c808e2e2f79e871/inc/class_parser.php#L2025) is used in the parser validation but it's deprecated as of PHP 8.0 [[ref](https://www.php.net/manual/en/function.libxml-disable-entity-loader.php)].

For PHP >= 8.0, there's no need to disable loading external entities. It may be safer to use
[`libxml_set_external_entity_loader()`](https://www.php.net/manual/en/function.libxml-set-external-entity-loader.php) or call the deprecated `libxml_disable_entity_loader()` only if PHP version is less than 8.0.

Oh, this issue was closed..

Edited: the prefixed `@` is pretty tricky.

**Comment by dvz** [comment]
Do you think we should replace `@` with a version condition there?

**Comment by yuliu** [comment]
Not necessary I think. The tricky leading `@` does the job well. It only needs a fix when PHP decides to print deprecation notices suppressed by `@`.

**Comment by yuliu** [comment]
Another two _undefined_ warnings.

1. Warning [2] Undefined array key "viewers" - Line: 328 - File: \inc\functions_forumlist.php PHP 8.0.7 (WINNT)

It may be fixed by adding the following line before [`/inc/functions_forumlist.php#L208`](https://github.com/mybb/mybb/blob/d291bf8bc4d5a3ee74c6961ad6128ae7bd18f873/inc/functions_forumlist.php#L208)
```$forum['viewers'] = 0;```


2.  Warning [2] Undefined variable $unapproved - Line: 7 - File: \inc\functions_forumlist.php(451) : eval()'d code PHP 8.0.7 (WINNT) & Warning [2] Trying to access array offset on value of type null - Line: 7 - File: \inc\functions_forumlist.php(451) : eval()'d code PHP 8.0.7 (WINNT)


My proposal is to amend the function `get_forum_unapproved($forum)` at [/inc/functions_forumlist.php#L560](https://github.com/mybb/mybb/blob/d291bf8bc4d5a3ee74c6961ad6128ae7bd18f873/inc/functions_forumlist.php#L560) with following

```php
/**
 * Fetch the number of unapproved posts, formatted, from a forum
 *
 * @param array $forum Array of information about the forum
 * @param bool $hideinfo Suppress the function output
 * @return array Array containing formatted string for posts and string for threads
 */
function get_forum_unapproved($forum, $hideinfo = false)
{
	if($hideinfo)
	{
		return array(
			"unapproved_posts" => '',
			"unapproved_threads" => ''
		);
	}

....snip....
```

... and change it's caller line at [/inc/functions_forumlist.php#L237](https://github.com/mybb/mybb/blob/d291bf8bc4d5a3ee74c6961ad6128ae7bd18f873/inc/functions_forumlist.php#L237) with the following...

```$unapproved = get_forum_unapproved($forum, $hideinfo);```

... and remove the 3 lines unsetting that var following that line.

**Comment by dvz** [comment]
Addressed in https://github.com/mybb/mybb/pull/4465/commits/ee19fb088afe061c037803c596acea1c20e11457:
- `$forum['viewers']` initialization moved to the top given existing references above the suggested line (related: #4466)
- `get_forum_unapproved()` condition added in the calling function instead (avoids unnecessary call to retrieve a simple array)

**Comment by yuliu** [comment]
1. Various warning about `can*` permissions: Warning [2] Undefined array key "caneditposts" - Line: 1986 - File: \inc\functions.php PHP 8.0.7 (WINNT)

https://github.com/mybb/mybb/blob/d291bf8bc4d5a3ee74c6961ad6128ae7bd18f873/inc/functions.php#L1986

Suggested fix - replace https://github.com/mybb/mybb/blob/d291bf8bc4d5a3ee74c6961ad6128ae7bd18f873/inc/functions.php#L1978-L1979 with
```php
				if(!isset($perms[$action]))
				{
					$perms[$action] = $value;
				}
				// Figure out the user permissions
				else if($value == 0)
```

2. Various warning about `can*` permissions: Warning [2] Undefined array key "caneditposts" - Line: 2011 - File: \inc\functions.php PHP 8.0.7 (WINNT)

https://github.com/mybb/mybb/blob/d291bf8bc4d5a3ee74c6961ad6128ae7bd18f873/inc/functions.php#L2007

Suggested fix - add the following before this line
```php
				if(!isset($perms[$action]))
				{
					$perms[$action] = $value;
				}
				else
				{
```

These fixes,,in my opinion, are not so good and not consistent. Further, the mod permission calculation seems improper which overrides group settings over individual's. Anyway, it may be because of the current whole permission system's disability.

**Comment by yuliu** [comment]
Warning [2] Undefined array key "threadprefix" - Line: 4 - File: \showthread.php(1217) : eval()'d code PHP 8.0.7 (WINNT)

https://github.com/mybb/mybb/blob/d291bf8bc4d5a3ee74c6961ad6128ae7bd18f873/showthread.php#L1217

Suggested fix - add an _else_ after https://github.com/mybb/mybb/blob/d291bf8bc4d5a3ee74c6961ad6128ae7bd18f873/showthread.php#L1187-L1195

```php
			else
			{
				$similar_thread['threadprefix'] = '';
			}
```

**Comment by yuliu** [comment]
Warning [2] Undefined variable $attachbox - Line: 43 - File: \newreply.php(1509) : eval()'d code PHP 8.0.7 (WINNT)
and the same in newthread.php

add an _else_ after https://github.com/mybb/mybb/blob/d291bf8bc4d5a3ee74c6961ad6128ae7bd18f873/newreply.php#L1181-L1182
and
https://github.com/mybb/mybb/blob/d291bf8bc4d5a3ee74c6961ad6128ae7bd18f873/newthread.php#L1022-L1025
```php
	else
	{
		$attachbox = '';
	}
```

I think there's more like these.. It might be better to go through code file by file.

**Comment by yuliu** [comment]
Warning [2] Undefined array key "HTTP_REFERER" - Line: 54 - File: \usercp.php PHP 8.0.7 (WINNT)

https://github.com/mybb/mybb/blob/d291bf8bc4d5a3ee74c6961ad6128ae7bd18f873/usercp.php#L54-L64

Looks like my server doesn't have such key sent to PHP and all redirect action seems semi-broken (others relying on `HTTP_REFERER` are in member.php & contact.php).

**Comment by yuliu** [comment]
Warning [2] Undefined property: MyLanguage::$theme_thumbnail - Line: 221 - File: \admin\modules\style\themes.php PHP 8.0.7 (WINNT)

There's no such language entry in `./inc/languages/english/admin/style_themes.lang.php` and maybe we can just add it.
