### ISSUE TITLE
Show 'edited by' Messages - moderators are not affected

### ISSUE THREAD

**Issue by Eldenroot** [mybb/mybb#4173]
https://community.mybb.com/thread-230145-post-1358450.html#pid1358450

**Comment by dvz** [comment]
There are additional problems with setting strings:
- the title for `showeditedby` is `Show 'edited by' Messages`, but should indicate it only applies to regular users (the admin/mod setting is independent)
- the `edited by a regular user` description suggests the editing user is checked, rather than the post author
- the title for `showeditedbyadmin` is `Show 'edited by' Message for Administrators and Moderators`, which may imply the viewing user is checked, rather than the post author
