### ISSUE TITLE
issue with recount&rebuild in admincp

### ISSUE THREAD

**Issue by effone** [mybb/mybb#4254]
Hello,

When i try to rebuild attachment thumbnails it gives me a white blank page without any error message not even in the PHP error_log so to get a clue about what is causing the issue i open /admin/modules/tools/recount_rebuild.php and add the top i add 

error_reporting(E_ALL);
ini_set(&quot;display_errors&quot;,1);
when i try again it shows me Notice: Undefined index: channels in functions_image.php on line 37

but i can't find what is causing the problem  help ....

Original thread: [issue with recount&rebuild in admincp](https://community.mybb.com/thread-231314.html)

**Comment by effone** [comment]
Note, same applies for `bits` as well. Need to address both `channels` and `bits`.

**Comment by euantorano** [comment]
Looks like there's already some code in for `channels`: https://github.com/mybb/mybb/blob/feature/inc/functions_image.php#L37

There isn't anything for `bits` though.

**Comment by Xazin** [comment]
From what I can tell, as Euan said, there is indeed missing an isset() check for bits, since when using getimagesize() not all type of files return channel and bits.

So in reality, the user is using MyBB 1.8.24, whereas the channel is being correctly checked in the feature branch and not in the version he is using. A check for bits should be implemented as well, which will solve the bug.
