### ISSUE TITLE
Absolute uploadspath fails due to MYBB_ROOT prefix on mime check

### ISSUE THREAD

**Issue by cjhewett** [mybb/mybb#4338]
To allow us to store the MyBB user uploaded attachments external to the webroot of the site we have set our `uploadspath` setting to an absolute directory e.g. `/foo/bar`

This all seems to work apart from the `finfo_open()`/`mime_content_type()` checks in [inc/functions_upload.php](https://github.com/mybb/mybb/blob/da7b32456e7b21c96f72c1093816c55cce249264/inc/functions_upload.php#L600) which prefixes the `uploadspath` path with `MYBB_ROOT`:

```php
$img_dimensions = @getimagesize($mybb->settings['uploadspath']."/".$filename);

$mime = "";
$file_path = $mybb->settings['uploadspath']."/".$filename;
if(function_exists("finfo_open"))
{
	$file_info = finfo_open(FILEINFO_MIME);
	list($mime, ) = explode(';', finfo_file($file_info, MYBB_ROOT.$file_path), 1);
	finfo_close($file_info);
}
else if(function_exists("mime_content_type"))
{
	$mime = mime_content_type($file_path);
}
```

Note how the `getimagesize()` **does not** prefix with `MYBB_ROOT` but then a few lines later in the call to `finfo_file()` it **does** prefix with it (and hence breaks for absolute directory paths).

**Comment by euantorano** [comment]
Good catch, looks like this has been broken for a long time now!

**Comment by lairdshaw** [comment]
The `uploads` setting seems generally to be assumed to be relative, probably because its default value (`./uploads`) is relative.

For example, a '../' is prepended to the `uploads` setting when IN_ADMINCP is true here:

https://github.com/mybb/mybb/blob/55e4afd96fe262f4fd0410fa61b5972883acca16/inc/functions_upload.php#L45-L52

and again here:

https://github.com/mybb/mybb/blob/55e4afd96fe262f4fd0410fa61b5972883acca16/inc/functions_upload.php#L103-L110

And _every_ time it occurs in [admin/modules/forum/attachments.php](https://github.com/mybb/mybb/blob/55e4afd96fe262f4fd0410fa61b5972883acca16/admin/modules/forum/attachments.php), it is currently preceded by `MYBB_ROOT`.

So, we probably need (as a team) to decide whether or not we want to permit absolute `uploads` paths, because if we do, then the changes will need to be slightly more extensive.

**Comment by dvz** [comment]
Related: #3754
