### ISSUE TITLE
Subforums viewers count not accounted for on index page

### ISSUE THREAD

**Issue by dvz** [mybb/mybb#4466]
The array key `viewing` at https://github.com/mybb/mybb/blob/mybb_1827/inc/functions_forumlist.php#L165-L168 does not exist; `viewers`, the key likely being referred to, is thus not added to the count, which results in views from subforums not being added to the parent's count (_x users browsing_ - _Show x viewing forum_ / `showforumviewing` setting).

**Comment by yuliu** [comment]
It looks like that the following lines at https://github.com/mybb/mybb/blob/feature/inc/functions_forumlist.php#L208-L211 (part 1) should be the the initial value of the number each forum's visitors
https://github.com/mybb/mybb/blob/d291bf8bc4d5a3ee74c6961ad6128ae7bd18f873/inc/functions_forumlist.php#L208-L211

and it should be assigned to `$forum['viewers']` before adding current forum's all sub forums' counters, if any, at https://github.com/mybb/mybb/blob/feature/inc/functions_forumlist.php#L165-L168 (part 2)
https://github.com/mybb/mybb/blob/d291bf8bc4d5a3ee74c6961ad6128ae7bd18f873/inc/functions_forumlist.php#L165-L168

where a variable is said to be fixed in this issue.

This means that part 1 should be placed before part 2.

**Comment by yuliu** [comment]
However, even with issues reported in the above two comments fixed, the _x users browsing - Show x viewing forum_ seems still broken at a specific forum/category level.

This very feature of _Show x viewing forum_, depending on a global variable `$forum_viewers` through `build_forumbits()`, only works on the index page (`index.php`) and the forum page (`forumdisplay.php`) for displaying a specific cat/forum did't show such information due to lacking of `$forum_viewers`.

Don't know if it's intended or a missing thing.

**Comment by dvz** [comment]
It may be acceptable as the setting belongs to the _Forum Home Options_ group.

**Comment by yuliu** [comment]
Ah, I see. I didn't keep in mind that option belongs to forum *Home* and then it's fine forum page doesn't show that info.
