### ISSUE TITLE
Fix PHP 8.0 compatibility problems (continued)

### ISSUE THREAD

**Issue by yuliu** [mybb/mybb#4485]
Following #4138, we'll continue fixing any PHP 8.0 compatibility issue.

**Comment by yuliu** [comment]
Warning [2] Trying to access array offset on value of type null - Line: 212 - File: \inc\class_session.php PHP 8.0.7 (WINNT)
File Line Function

https://github.com/mybb/mybb/blob/89ba6fd39fca4ede328f69deca9aba7b57f2c5d1/inc/class_session.php#L211-L215

Warning [2] Trying to access array offset on value of type null - Line: 222 - File: \inc\class_session.php PHP 8.0.7 (WINNT)
File Line Function

https://github.com/mybb/mybb/blob/89ba6fd39fca4ede328f69deca9aba7b57f2c5d1/inc/class_session.php#L221-L225

It looks like that `/inc/init.php` in which the globals `$date_formats` and `$time_formats` are defined is not included for the upgrade script.

This also affects the Merge System.

**Comment by yuliu** [comment]
Warning [2] Undefined array key "requires_deactivated_plugins" - Line: 350 - File: \install\upgrade.php PHP 8.0.7 (WINNT)

https://github.com/mybb/mybb/blob/89ba6fd39fca4ede328f69deca9aba7b57f2c5d1/install/upgrade.php#L350

Not all upgrade scripts have `$upgrade_detail['requires_deactivated_plugins']` defined.

**Comment by yuliu** [comment]
Warning [2] Trying to access array offset on value of type null - Line: 772 - File: \install\upgrade.php PHP 8.0.7 (WINNT)
Warning [2] Undefined array key "revert_all_themes" - Line: 772 - File: \install\upgrade.php PHP 8.0.7 (WINNT)
Warning [2] Undefined array key "revert_all_settings" - Line: 772 - File: \install\upgrade.php PHP 8.0.7 (WINNT)

https://github.com/mybb/mybb/blob/89ba6fd39fca4ede328f69deca9aba7b57f2c5d1/install/upgrade.php#L772

It seems that the global `$system_upgrade_detail` hasn't been read from db before reading it in this line.

**Comment by yuliu** [comment]
Warning [2] Undefined variable $function - Line: 753 - File: \install\upgrade.php PHP 8.0.7 (WINNT)

https://github.com/mybb/mybb/blob/89ba6fd39fca4ede328f69deca9aba7b57f2c5d1/install/upgrade.php#L753-L756

**Comment by yuliu** [comment]
Warning [2] Undefined array key 1 - Line: 394 - File: \install\upgrade.php PHP 8.0.7 (WINNT)

https://github.com/mybb/mybb/blob/89ba6fd39fca4ede328f69deca9aba7b57f2c5d1/install/upgrade.php#L394-L399

**Comment by yuliu** [comment]
Warning [2] Undefined variable $settings - Line: 1010 - File: \install\upgrade.php PHP 8.0.7 (WINNT)

`$settings` was unset here:
https://github.com/mybb/mybb/blob/89ba6fd39fca4ede328f69deca9aba7b57f2c5d1/install/upgrade.php#L1004

.. and after that without creating it, an append assignment is called:
https://github.com/mybb/mybb/blob/89ba6fd39fca4ede328f69deca9aba7b57f2c5d1/install/upgrade.php#L1010

**Comment by yuliu** [comment]
Warning [2] Undefined variable $contents - Line: 592 - File: \install\upgrade.php PHP 8.0.7 (WINNT)

https://github.com/mybb/mybb/blob/89ba6fd39fca4ede328f69deca9aba7b57f2c5d1/install/upgrade.php#L592

**Comment by yuliu** [comment]
The above 6 compatibility issues are all from the upgrade script, sorry about posting them in separate comments.

**Comment by yuliu** [comment]
When viewing a Diff Report of a template.

Warning [2] Undefined array key "sid1" - Line: 1534 - File: \admin\modules\style\templates.php PHP 8.0.7 (WINNT)

https://github.com/mybb/mybb/blob/89ba6fd39fca4ede328f69deca9aba7b57f2c5d1/admin/modules/style/templates.php#L1533-L1537

Warning [2] Undefined array key "from" - Line: 1553 - File: \admin\modules\style\templates.php PHP 8.0.7 (WINNT)

https://github.com/mybb/mybb/blob/89ba6fd39fca4ede328f69deca9aba7b57f2c5d1/admin/modules/style/templates.php#L1553-L1556

**Comment by dvz** [comment]
`Undefined variable $feb_fix, inc/functions_calendar.php, 588` (https://community.mybb.com/thread-234123-post-1372760.html#pid1372760)

**Comment by yuliu** [comment]
Plugins that don't have a `codename` or `guid` in their `*_info()` functions may break AdminCP > Plugins > Plugin Updates.

Warning [2] Undefined array key "codename" - Line: 222 - File: \admin\modules\config\plugins.php PHP 8.1.0 (WINNT)

https://github.com/mybb/mybb/blob/89ba6fd39fca4ede328f69deca9aba7b57f2c5d1/admin/modules/config/plugins.php#L222-L233

**Comment by yuliu** [comment]
Warning [2] Uninitialized string offset XXX - Line: 423 - File: \inc\class_mailhandler.php PHP 8.1.0 (WINNT)

https://github.com/mybb/mybb/blob/89ba6fd39fca4ede328f69deca9aba7b57f2c5d1/inc/class_mailhandler.php#L423-L427

Suggested fix:
```php
				if($newpos != $len)
				{
					while(ord($string[$newpos]) >= 0x80 && ord($string[$newpos]) < 0xC0)
					{
						// Reduce len until it's safe to split UTF-8.
						$newpos--;
					}
				}
```

Although being a workaround, it won't get a perfect fix, as we plan to use a 3rd party mailer in v1.9.

BTW, the indentation in line 419 uses spaces.
https://github.com/mybb/mybb/blob/89ba6fd39fca4ede328f69deca9aba7b57f2c5d1/inc/class_mailhandler.php#L419

**Comment by ajmcello** [comment]
I'm using php 8.1, pgsql 14.2, Ubuntu, apache. I did the install a couple a couple days ago with mybb 1830. So this are all relevant to that release. I'm curious if I should try "feature" from github? I read that trying 1.9 will probably break too many extensions, so I stayed away from that.

If there's a way to turn on better logging for php, apache, and mybb, please let me know! I'll be glad to help as much as I can, but I may get frustrated, give up, and fall off the earth.

Under ACP->Search System, I get the following:

Warning [2] Undefined property: MyLanguage::$setting_searchtype_standard - Line: 2 - File: admin/modules/config/settings.php(1540) : eval()'d code PHP 8.1.0 (Linux)
File Line Function
/inc/class_error.php 153 errorHandler->error
/admin/modules/config/settings.php(1540) : eval()'d code 2 errorHandler->error_callback
/admin/modules/config/settings.php 1540 eval
/admin/index.php 825 require

Under registration, or member.php, I get:

Warning [2] Trying to access array offset on value of type bool - Line: 844 - File: member.php PHP 8.1.0 (Linux)
File Line Function
/inc/class_error.php 153 errorHandler->error
/member.php 844 errorHandler->error_callback
Warning [2] Trying to access array offset on value of type bool - Line: 846 - File: member.php PHP 8.1.0 (Linux)
File Line Function
/inc/class_error.php 153 errorHandler->error
/member.php 846 errorHandler->error_callback
Warning [2] Undefined array key 1 - Line: 906 - File: member.php PHP 8.1.0 (Linux)
File Line Function
/inc/class_error.php 153 errorHandler->error
/member.php 906 errorHandler->error_callback
Warning [2] Undefined array key 1 - Line: 906 - File: member.php PHP 8.1.0 (Linux)
File Line Function
/inc/class_error.php 153 errorHandler->error
/member.php 906 errorHandler->error_callback

And captcha doesn't work, I get:


[*]The image verification code that you entered was incorrect. Please enter the code exactly how it appears in the image.


And I couldn't register a username or email, it was always highlighted in red.

I disabled Captcha and I got further.

I'm not downgrading, and I guess it sounds like a lot of the forum wares are dying. My reluctance for phpBB is because it was SQL injected and I lost my forum years ago with no way of recovering. This time around, it seemed like MyBB was a good alternative choice.

Seems to mostly work, but I don't know what other problems might pop up.

What is "feature" on the github repo? It seems this has some newer updates than 1830. 
[error_log.txt](https://github.com/mybb/mybb/files/8288328/error_log.txt)

**Comment by dvz** [comment]
The `feature` branch contains code to be included in the next maintenance release.

I've added fixes for the errors in #4519.

You can create a support thread on the Forums for the CAPTCHA problem - it may be unrelated to PHP 8 (which type was selected when the error occurred?).

**Comment by ajmcello** [comment]
> The `feature` branch contains code to be included in the next maintenance release.
> 
> I've added fixes for the errors in #4519.
> 
> You can create a support thread on the Forums for the CAPTCHA problem - it may be unrelated to PHP 8 (which type was selected when the error occurred?).

Thanks for getting back quickly! I'll take a look at your fixes, and apply them. I'll likely encounter more, I'll keep a log and if I can figure out how to correct them so they work with PHP 8.1.

I'll post my progress here for fixes. I'm not a coder, but I can usually update and fix simple things (though it may not be the proper way).

**Comment by jayk1961** [comment]
Backup error:

<html><body>
<br>
<font size="1">

( ! )  Fatal error: Uncaught TypeError: PDO::quote(): Argument #1 ($string)  must be of type string, resource given in  /var/www/vhost/XXX.com/inc/AbstractPdoDbDriver.php on line 676
--



1 | 0.0000 | 421360 | {main}(  ) | .../index.php:0
2 | 0.0431 | 736520 | require( '/var/www/vhost/XXX.com/admin/modules/tools/backupdb.php ) | .../index.php:825
3 | 0.0710 | 743168 | AbstractPdoDbDriver->escape_string( $string = resource(10) of type (stream) ) | .../backupdb.php:256
4 | 0.0710 | 743168 | quote( $string = resource(10) of type (stream) ) | .../AbstractPdoDbDriver.php:676

</font>
</body>
</html>( ! ) Fatal error: Uncaught TypeError: PDO::[quote](http://www.php.net/PDO.quote)(): Argument #1 ($string) must be of type string, resource given in /var/www/vhost/XXX.com/inc/AbstractPdoDbDriver.php on line 676
( ! ) TypeError: PDO::quote(): Argument #1 ($string) must be of type string, resource given in /var/www/vhost/XXX.com/inc/AbstractPdoDbDriver.php on line 676
Call Stack
#	Time	Memory	Function	Location
1	0.0000	421360	{main}( )	.../index.php:0
2	0.0431	736520	require( '/var/www/vhost/XXX.com/admin/modules/tools/backupdb.php )	.../index.php:825
3	0.0710	743168	AbstractPdoDbDriver->escape_string( $string = resource(10) of type (stream) )	.../backupdb.php:256
4	0.0710	743168	quote( $string = resource(10) of type (stream) )	.../AbstractPdoDbDriver.php:676

**Comment by ajmcello** [comment]
Admin->Forum Posts

Create/Save Change forum displays these errors:

<html>
<body>
<div class="php_warning" style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong>Warning</strong><span> </span>[2] Undefined array key 1 - Line: 269 - File: admin/inc/functions.php PHP 8.1.2 (Linux)<br>

Warning [2] Undefined array key 1 - Line: 269 - File: admin/inc/functions.php PHP 8.1.2 (Linux)

File | Line | Function
-- | -- | --
/inc/class_error.php | 153 | errorHandler->error
Warning [2] Trying to access array offset on value of type null - Line: 271 - File: admin/inc/functions.php PHP 8.1.2 (Linux)

/admin/inc/functions.php | 269 | errorHandler->error_callback
Warning [2] Trying to access array offset on value of type null - Line: 280 - File: admin/inc/functions.php PHP 8.1.2 (Linux)

/admin/modules/forum/management.php | 1532 | save_quick_perms
Warning [2] Trying to access array offset on value of type null - Line: 289 - File: admin/inc/functions.php PHP 8.1.2 (Linux)

/admin/index.php | 825 | require
Warning [2] Trying to access array offset on value of type null - Line: 298 - File: admin/inc/functions.php PHP 8.1.2 (Linux)

</div>
</body>
</html>

**Comment by ajmcello** [comment]
Thanks!

**Comment by cjhewett** [comment]
Reposting https://github.com/mybb/mybb/issues/4138#issuecomment-872245095 from the closed PHP 8 list as it doesn't look like it was resolved and we are still having error emails triggered by it occasionally:

* https://github.com/mybb/mybb/blob/master/inc/class_session.php#L31 `Undefined array key "HTTP_USER_AGENT" `

**Comment by dvz** [comment]
- [x] passing `false` (a potential result of `fopen()`) to `fclose()`
  - https://community.mybb.com/thread-234848.html
