### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by cronlabspl** [mybb/mybb#4507]
https://github.com/mybb/mybb/blob/4dcc29f4e3199b33c68d16de19db5642a2fd1547/admin/inc/class_form.php#L41

Why do we need to check this, if - in function declaration we explicitly assign value to this `var`?

**Comment by yuliu** [comment]
In the function declaration the variable `$allow_uploads` will have a default value `false` if it's not given when the function is called. The variable could be any value from the caller and that's why it'll still need to be checked. I'm not sure if it's the answer you expect.

By the way, we use GitHub issue trackers for confirmed issues, and if you have problems and questions about MyBB software, better create a thread in the support forum https://community.mybb.com/forum-176.html . Oh, please also read https://mybb.com/get-involved/ for further information on contributing to MyBB. Thanks!

**Comment by cronlabspl** [comment]
@yuliu yes. Thats exactly what answers my question 100%. Thanks 👍 Closing this.
