### ISSUE TITLE
Bug when removing a member from a group that could become invisible

### ISSUE THREAD

**Issue by Walter-Correa** [mybb/mybb#4801]
If the member is in a group that allows them to be invisible, in their profile they activate invisibility, then the member is removed from this group or goes to a group that cannot be invisible:

It remains marked as invisible in the database, but this has no effect. Everything ok, this was as expected!

The problem is that when the member is viewing a forum, his name appears in the list of those viewing it and also **-1 Invisible Users** appear.

**Screenshot:** https://prnt.sc/ZDeZc99PsVcg

**This only disappears when manually removing the member's invisibility in the database.**

**Comment by Walter-Correa** [comment]
Until this is corrected I will hide this information in **forumdisplay_userbrowsing** and **showthread_userbrowsing**!
`<span class="smalltext">{$lang->users_browsing_forum} {$onlinemembers}<!--{$onlinesep}{$invisonline}-->{$onlinesep2}{$guestsonline}</span><br />`

**Comment by dvz** [comment]
The `canbeinvisible` conditions added in #4065:
```php
if($user['invisible'] == 1 && $mybb->usergroup['canbeinvisible'] == 1)
```
seem incorrect, as they only refer to the viewing user.

We can remove them to fix the count error for users with { `invisible = 1` & `canbeinvisible = 0` } that may result in `-1` because of:
- https://github.com/mybb/mybb/blob/526feb94120cd63a30b286f22359df92379b6405/forumdisplay.php#L337-L341
- https://github.com/mybb/mybb/blob/526feb94120cd63a30b286f22359df92379b6405/showthread.php#L1617-L1621

This would still leave updating `mybb_users.invisible` after usergroup changes.
