### ISSUE TITLE
Maximum times a user can vote on a poll

### ISSUE THREAD

**Issue by Polarbear541** [mybb/mybb#596]
So as per the original roadmap thread, I have been working on adding an option which allows you to specify the maximum number of times a user can vote on a poll. But after seeing #583 I'm wondering whether I've misunderstood the idea.

My interpretation is shown below:
![image](https://cloud.githubusercontent.com/assets/2014518/3095400/67c5a522-e5c7-11e3-9234-ae599ece2151.png)
Where the user can vote multiple times on the same poll.

My question is will this be useful and should I continue to work on it? :P

**Comment by JN-Jones** [comment]
@mybb/developers @mybb/management @mybb/sqa As we're already at 1.8.8 without ever getting this done I'm not sure whether we really need this. Especially since we decided to concentrate on 2.0 and stop adding features to 1.8. While @Polarbear541 had done some work on this (#1095) it doesn't look like that PR was near done. So I'd propose closing this and instead keep it in mind for 2.0.

**Comment by Stefan-ST** [comment]
It's certainly not a feature that has been requested many times.

**Comment by JN-Jones** [comment]
@euantorano Fine with closing this too?

**Comment by euantorano** [comment]
Yep, no objections here.
