### ISSUE TITLE
Subject  Max. Char. error on preview

### ISSUE THREAD

**Issue by JN-Jones** [mybb/mybb#907]
if the thread subject has more than 85 characters, mybb will remove the "RE: " part while posting replies... but the same doesnt work if we preview the post in such threads... it returns the usual error like "Please correct the following errors before continuing: The subject is too long. Please enter a subject shorter than 85 characters (currently 89)." on preview....

Original thread: [Subject  Max. Char. error on preview](http://community.mybb.com/thread-155845.html)

**Comment by Evenprime** [comment]
I've tracked down the issue to a missing line of code for the posthandler created for post previews in newreply.php

It is a very simple fix that should have no negative side effects, because the same setting is later used to actually store the reply and therefore all validation constraints attached to that setting have to be respected anyway.
